// Code generated by protoc-gen-gcraft. DO NOT EDIT.
// source: user_manager_service.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	protocol "github.com/superp00t/gophercraft/bnet/bgs/protocol"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubscribeRequest struct {
	AgentId              *protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	ObjectId             *uint64            `protobuf:"varint,2,req,name=object_id,json=objectId" json:"object_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_830181c62db76447, []int{0}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetAgentId() *protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *SubscribeRequest) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

type SubscribeResponse struct {
	BlockedPlayers       []*BlockedPlayer `protobuf:"bytes,1,rep,name=blocked_players,json=blockedPlayers" json:"blocked_players,omitempty"`
	RecentPlayers        []*RecentPlayer  `protobuf:"bytes,2,rep,name=recent_players,json=recentPlayers" json:"recent_players,omitempty"`
	Role                 []*protocol.Role `protobuf:"bytes,3,rep,name=role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SubscribeResponse) Reset()         { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()    {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_830181c62db76447, []int{1}
}

func (m *SubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeResponse.Unmarshal(m, b)
}
func (m *SubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeResponse.Marshal(b, m, deterministic)
}
func (m *SubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeResponse.Merge(m, src)
}
func (m *SubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeResponse.Size(m)
}
func (m *SubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeResponse proto.InternalMessageInfo

func (m *SubscribeResponse) GetBlockedPlayers() []*BlockedPlayer {
	if m != nil {
		return m.BlockedPlayers
	}
	return nil
}

func (m *SubscribeResponse) GetRecentPlayers() []*RecentPlayer {
	if m != nil {
		return m.RecentPlayers
	}
	return nil
}

func (m *SubscribeResponse) GetRole() []*protocol.Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type UnsubscribeRequest struct {
	AgentId              *protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	ObjectId             *uint64            `protobuf:"varint,2,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UnsubscribeRequest) Reset()         { *m = UnsubscribeRequest{} }
func (m *UnsubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeRequest) ProtoMessage()    {}
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_830181c62db76447, []int{2}
}

func (m *UnsubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeRequest.Unmarshal(m, b)
}
func (m *UnsubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeRequest.Marshal(b, m, deterministic)
}
func (m *UnsubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeRequest.Merge(m, src)
}
func (m *UnsubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeRequest.Size(m)
}
func (m *UnsubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeRequest proto.InternalMessageInfo

func (m *UnsubscribeRequest) GetAgentId() *protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *UnsubscribeRequest) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

type AddRecentPlayersRequest struct {
	Players              []*RecentPlayer    `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
	AgentId              *protocol.EntityId `protobuf:"bytes,2,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	Program              *uint32            `protobuf:"varint,3,opt,name=program" json:"program,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AddRecentPlayersRequest) Reset()         { *m = AddRecentPlayersRequest{} }
func (m *AddRecentPlayersRequest) String() string { return proto.CompactTextString(m) }
func (*AddRecentPlayersRequest) ProtoMessage()    {}
func (*AddRecentPlayersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_830181c62db76447, []int{3}
}

func (m *AddRecentPlayersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRecentPlayersRequest.Unmarshal(m, b)
}
func (m *AddRecentPlayersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRecentPlayersRequest.Marshal(b, m, deterministic)
}
func (m *AddRecentPlayersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRecentPlayersRequest.Merge(m, src)
}
func (m *AddRecentPlayersRequest) XXX_Size() int {
	return xxx_messageInfo_AddRecentPlayersRequest.Size(m)
}
func (m *AddRecentPlayersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRecentPlayersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRecentPlayersRequest proto.InternalMessageInfo

func (m *AddRecentPlayersRequest) GetPlayers() []*RecentPlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *AddRecentPlayersRequest) GetAgentId() *protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *AddRecentPlayersRequest) GetProgram() uint32 {
	if m != nil && m.Program != nil {
		return *m.Program
	}
	return 0
}

type ClearRecentPlayersRequest struct {
	AgentId              *protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	Program              *uint32            `protobuf:"varint,2,opt,name=program" json:"program,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ClearRecentPlayersRequest) Reset()         { *m = ClearRecentPlayersRequest{} }
func (m *ClearRecentPlayersRequest) String() string { return proto.CompactTextString(m) }
func (*ClearRecentPlayersRequest) ProtoMessage()    {}
func (*ClearRecentPlayersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_830181c62db76447, []int{4}
}

func (m *ClearRecentPlayersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearRecentPlayersRequest.Unmarshal(m, b)
}
func (m *ClearRecentPlayersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearRecentPlayersRequest.Marshal(b, m, deterministic)
}
func (m *ClearRecentPlayersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearRecentPlayersRequest.Merge(m, src)
}
func (m *ClearRecentPlayersRequest) XXX_Size() int {
	return xxx_messageInfo_ClearRecentPlayersRequest.Size(m)
}
func (m *ClearRecentPlayersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearRecentPlayersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearRecentPlayersRequest proto.InternalMessageInfo

func (m *ClearRecentPlayersRequest) GetAgentId() *protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *ClearRecentPlayersRequest) GetProgram() uint32 {
	if m != nil && m.Program != nil {
		return *m.Program
	}
	return 0
}

type BlockPlayerRequest struct {
	AgentId              *protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	TargetId             *protocol.EntityId `protobuf:"bytes,2,req,name=target_id,json=targetId" json:"target_id,omitempty"`
	Role                 *uint32            `protobuf:"varint,3,opt,name=role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BlockPlayerRequest) Reset()         { *m = BlockPlayerRequest{} }
func (m *BlockPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*BlockPlayerRequest) ProtoMessage()    {}
func (*BlockPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_830181c62db76447, []int{5}
}

func (m *BlockPlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockPlayerRequest.Unmarshal(m, b)
}
func (m *BlockPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockPlayerRequest.Marshal(b, m, deterministic)
}
func (m *BlockPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockPlayerRequest.Merge(m, src)
}
func (m *BlockPlayerRequest) XXX_Size() int {
	return xxx_messageInfo_BlockPlayerRequest.Size(m)
}
func (m *BlockPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockPlayerRequest proto.InternalMessageInfo

func (m *BlockPlayerRequest) GetAgentId() *protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *BlockPlayerRequest) GetTargetId() *protocol.EntityId {
	if m != nil {
		return m.TargetId
	}
	return nil
}

func (m *BlockPlayerRequest) GetRole() uint32 {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return 0
}

type UnblockPlayerRequest struct {
	AgentId              *protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	TargetId             *protocol.EntityId `protobuf:"bytes,2,req,name=target_id,json=targetId" json:"target_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UnblockPlayerRequest) Reset()         { *m = UnblockPlayerRequest{} }
func (m *UnblockPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*UnblockPlayerRequest) ProtoMessage()    {}
func (*UnblockPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_830181c62db76447, []int{6}
}

func (m *UnblockPlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnblockPlayerRequest.Unmarshal(m, b)
}
func (m *UnblockPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnblockPlayerRequest.Marshal(b, m, deterministic)
}
func (m *UnblockPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnblockPlayerRequest.Merge(m, src)
}
func (m *UnblockPlayerRequest) XXX_Size() int {
	return xxx_messageInfo_UnblockPlayerRequest.Size(m)
}
func (m *UnblockPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnblockPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnblockPlayerRequest proto.InternalMessageInfo

func (m *UnblockPlayerRequest) GetAgentId() *protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *UnblockPlayerRequest) GetTargetId() *protocol.EntityId {
	if m != nil {
		return m.TargetId
	}
	return nil
}

type BlockedPlayerAddedNotification struct {
	Player               *BlockedPlayer     `protobuf:"bytes,1,req,name=player" json:"player,omitempty"`
	GameAccountId        *protocol.EntityId `protobuf:"bytes,2,opt,name=game_account_id,json=gameAccountId" json:"game_account_id,omitempty"`
	AccountId            *protocol.EntityId `protobuf:"bytes,3,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BlockedPlayerAddedNotification) Reset()         { *m = BlockedPlayerAddedNotification{} }
func (m *BlockedPlayerAddedNotification) String() string { return proto.CompactTextString(m) }
func (*BlockedPlayerAddedNotification) ProtoMessage()    {}
func (*BlockedPlayerAddedNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_830181c62db76447, []int{7}
}

func (m *BlockedPlayerAddedNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockedPlayerAddedNotification.Unmarshal(m, b)
}
func (m *BlockedPlayerAddedNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockedPlayerAddedNotification.Marshal(b, m, deterministic)
}
func (m *BlockedPlayerAddedNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockedPlayerAddedNotification.Merge(m, src)
}
func (m *BlockedPlayerAddedNotification) XXX_Size() int {
	return xxx_messageInfo_BlockedPlayerAddedNotification.Size(m)
}
func (m *BlockedPlayerAddedNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockedPlayerAddedNotification.DiscardUnknown(m)
}

var xxx_messageInfo_BlockedPlayerAddedNotification proto.InternalMessageInfo

func (m *BlockedPlayerAddedNotification) GetPlayer() *BlockedPlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *BlockedPlayerAddedNotification) GetGameAccountId() *protocol.EntityId {
	if m != nil {
		return m.GameAccountId
	}
	return nil
}

func (m *BlockedPlayerAddedNotification) GetAccountId() *protocol.EntityId {
	if m != nil {
		return m.AccountId
	}
	return nil
}

type BlockedPlayerRemovedNotification struct {
	Player               *BlockedPlayer     `protobuf:"bytes,1,req,name=player" json:"player,omitempty"`
	GameAccountId        *protocol.EntityId `protobuf:"bytes,2,opt,name=game_account_id,json=gameAccountId" json:"game_account_id,omitempty"`
	AccountId            *protocol.EntityId `protobuf:"bytes,3,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BlockedPlayerRemovedNotification) Reset()         { *m = BlockedPlayerRemovedNotification{} }
func (m *BlockedPlayerRemovedNotification) String() string { return proto.CompactTextString(m) }
func (*BlockedPlayerRemovedNotification) ProtoMessage()    {}
func (*BlockedPlayerRemovedNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_830181c62db76447, []int{8}
}

func (m *BlockedPlayerRemovedNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockedPlayerRemovedNotification.Unmarshal(m, b)
}
func (m *BlockedPlayerRemovedNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockedPlayerRemovedNotification.Marshal(b, m, deterministic)
}
func (m *BlockedPlayerRemovedNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockedPlayerRemovedNotification.Merge(m, src)
}
func (m *BlockedPlayerRemovedNotification) XXX_Size() int {
	return xxx_messageInfo_BlockedPlayerRemovedNotification.Size(m)
}
func (m *BlockedPlayerRemovedNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockedPlayerRemovedNotification.DiscardUnknown(m)
}

var xxx_messageInfo_BlockedPlayerRemovedNotification proto.InternalMessageInfo

func (m *BlockedPlayerRemovedNotification) GetPlayer() *BlockedPlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *BlockedPlayerRemovedNotification) GetGameAccountId() *protocol.EntityId {
	if m != nil {
		return m.GameAccountId
	}
	return nil
}

func (m *BlockedPlayerRemovedNotification) GetAccountId() *protocol.EntityId {
	if m != nil {
		return m.AccountId
	}
	return nil
}

type RecentPlayersAddedNotification struct {
	Player               []*RecentPlayer `protobuf:"bytes,1,rep,name=player" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RecentPlayersAddedNotification) Reset()         { *m = RecentPlayersAddedNotification{} }
func (m *RecentPlayersAddedNotification) String() string { return proto.CompactTextString(m) }
func (*RecentPlayersAddedNotification) ProtoMessage()    {}
func (*RecentPlayersAddedNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_830181c62db76447, []int{9}
}

func (m *RecentPlayersAddedNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecentPlayersAddedNotification.Unmarshal(m, b)
}
func (m *RecentPlayersAddedNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecentPlayersAddedNotification.Marshal(b, m, deterministic)
}
func (m *RecentPlayersAddedNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecentPlayersAddedNotification.Merge(m, src)
}
func (m *RecentPlayersAddedNotification) XXX_Size() int {
	return xxx_messageInfo_RecentPlayersAddedNotification.Size(m)
}
func (m *RecentPlayersAddedNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_RecentPlayersAddedNotification.DiscardUnknown(m)
}

var xxx_messageInfo_RecentPlayersAddedNotification proto.InternalMessageInfo

func (m *RecentPlayersAddedNotification) GetPlayer() []*RecentPlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

type RecentPlayersRemovedNotification struct {
	Player               []*RecentPlayer `protobuf:"bytes,1,rep,name=player" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RecentPlayersRemovedNotification) Reset()         { *m = RecentPlayersRemovedNotification{} }
func (m *RecentPlayersRemovedNotification) String() string { return proto.CompactTextString(m) }
func (*RecentPlayersRemovedNotification) ProtoMessage()    {}
func (*RecentPlayersRemovedNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_830181c62db76447, []int{10}
}

func (m *RecentPlayersRemovedNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecentPlayersRemovedNotification.Unmarshal(m, b)
}
func (m *RecentPlayersRemovedNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecentPlayersRemovedNotification.Marshal(b, m, deterministic)
}
func (m *RecentPlayersRemovedNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecentPlayersRemovedNotification.Merge(m, src)
}
func (m *RecentPlayersRemovedNotification) XXX_Size() int {
	return xxx_messageInfo_RecentPlayersRemovedNotification.Size(m)
}
func (m *RecentPlayersRemovedNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_RecentPlayersRemovedNotification.DiscardUnknown(m)
}

var xxx_messageInfo_RecentPlayersRemovedNotification proto.InternalMessageInfo

func (m *RecentPlayersRemovedNotification) GetPlayer() []*RecentPlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

func init() {
	proto.RegisterType((*SubscribeRequest)(nil), "bgs.protocol.user_manager.v1.SubscribeRequest")
	proto.RegisterType((*SubscribeResponse)(nil), "bgs.protocol.user_manager.v1.SubscribeResponse")
	proto.RegisterType((*UnsubscribeRequest)(nil), "bgs.protocol.user_manager.v1.UnsubscribeRequest")
	proto.RegisterType((*AddRecentPlayersRequest)(nil), "bgs.protocol.user_manager.v1.AddRecentPlayersRequest")
	proto.RegisterType((*ClearRecentPlayersRequest)(nil), "bgs.protocol.user_manager.v1.ClearRecentPlayersRequest")
	proto.RegisterType((*BlockPlayerRequest)(nil), "bgs.protocol.user_manager.v1.BlockPlayerRequest")
	proto.RegisterType((*UnblockPlayerRequest)(nil), "bgs.protocol.user_manager.v1.UnblockPlayerRequest")
	proto.RegisterType((*BlockedPlayerAddedNotification)(nil), "bgs.protocol.user_manager.v1.BlockedPlayerAddedNotification")
	proto.RegisterType((*BlockedPlayerRemovedNotification)(nil), "bgs.protocol.user_manager.v1.BlockedPlayerRemovedNotification")
	proto.RegisterType((*RecentPlayersAddedNotification)(nil), "bgs.protocol.user_manager.v1.RecentPlayersAddedNotification")
	proto.RegisterType((*RecentPlayersRemovedNotification)(nil), "bgs.protocol.user_manager.v1.RecentPlayersRemovedNotification")
}

func init() { proto.RegisterFile("user_manager_service.proto", fileDescriptor_830181c62db76447) }

var fileDescriptor_830181c62db76447 = []byte{
	// 833 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x55, 0xcf, 0x6f, 0xe2, 0x46,
	0x14, 0xae, 0x4d, 0x94, 0xc0, 0x23, 0x24, 0x74, 0x4a, 0x52, 0xe2, 0x56, 0x11, 0xf2, 0xa1, 0x42,
	0xa1, 0xb5, 0x13, 0xa2, 0xa8, 0x3d, 0x54, 0x91, 0x42, 0x92, 0x56, 0xa8, 0x6d, 0x92, 0x9a, 0xe6,
	0x52, 0xa9, 0x42, 0xfe, 0x31, 0x71, 0xdc, 0x80, 0xc7, 0x3b, 0x33, 0xb0, 0x42, 0x2b, 0xad, 0x56,
	0x1c, 0x73, 0xda, 0x3f, 0x64, 0xef, 0x7b, 0xd8, 0x7f, 0x65, 0xb5, 0xa7, 0xfd, 0x27, 0xb8, 0xad,
	0xb0, 0x01, 0xd9, 0x38, 0x18, 0x88, 0x22, 0xad, 0xb4, 0x37, 0x3c, 0xbc, 0xef, 0xfb, 0xde, 0x7b,
	0xf3, 0xde, 0x37, 0x20, 0x75, 0x18, 0xa6, 0xcd, 0xb6, 0xee, 0xea, 0x36, 0xa6, 0x4d, 0x86, 0x69,
	0xd7, 0x31, 0xb1, 0xe2, 0x51, 0xc2, 0x09, 0xfa, 0xde, 0xb0, 0x59, 0xf0, 0xd3, 0x24, 0x2d, 0x25,
	0x1c, 0xa8, 0x74, 0x0f, 0xa4, 0x62, 0x04, 0xc9, 0x7b, 0x1e, 0x1e, 0x05, 0x4b, 0x08, 0xbb, 0xdc,
	0xe1, 0xbd, 0xc8, 0x59, 0x9e, 0x92, 0x16, 0x8e, 0x9c, 0x6c, 0x52, 0xcf, 0x0c, 0x1f, 0xc8, 0x06,
	0xe4, 0x1b, 0x1d, 0x83, 0x99, 0xd4, 0x31, 0xb0, 0x86, 0x9f, 0x75, 0x30, 0xe3, 0xe8, 0x00, 0xd2,
	0xba, 0x8d, 0x5d, 0xde, 0x74, 0xac, 0xa2, 0x50, 0x12, 0xca, 0xd9, 0xea, 0xb6, 0x12, 0xc9, 0xea,
	0xdc, 0x97, 0xaa, 0x5b, 0xda, 0x9a, 0x1f, 0x57, 0xb7, 0xd0, 0x77, 0x90, 0x21, 0xc6, 0xff, 0xd8,
	0xf4, 0x31, 0x62, 0x49, 0x2c, 0xaf, 0x68, 0xe9, 0xe0, 0xa0, 0x6e, 0xc9, 0x1f, 0x05, 0xf8, 0x3a,
	0x24, 0xc2, 0x3c, 0xe2, 0x32, 0x8c, 0xfe, 0x81, 0x4d, 0xa3, 0x45, 0xcc, 0x3b, 0x6c, 0x35, 0xbd,
	0x96, 0xde, 0xc3, 0x94, 0x15, 0x85, 0x52, 0xaa, 0x9c, 0xad, 0x56, 0x94, 0xa4, 0x16, 0x28, 0xb5,
	0x00, 0x74, 0xe5, 0x63, 0xb4, 0x0d, 0x23, 0xfc, 0xc9, 0xd0, 0xdf, 0xb0, 0x41, 0xb1, 0x39, 0x4c,
	0x7e, 0x4c, 0x2a, 0xfa, 0xa4, 0x7b, 0xc9, 0xa4, 0x9a, 0x8f, 0x19, 0x71, 0xe6, 0x68, 0xe8, 0x8b,
	0xa1, 0x1f, 0x60, 0x65, 0xd8, 0xc7, 0x62, 0xca, 0x27, 0x42, 0x51, 0x22, 0x8d, 0xb4, 0xb0, 0xe6,
	0xff, 0x2f, 0x5b, 0x80, 0xae, 0x5d, 0xf6, 0xf4, 0xcd, 0x14, 0x22, 0xcd, 0x7c, 0x23, 0xc0, 0xb7,
	0x27, 0x96, 0x15, 0x4e, 0x98, 0x8d, 0xb5, 0xce, 0x60, 0x2d, 0xda, 0xca, 0x65, 0xaa, 0x1e, 0x43,
	0x23, 0x19, 0x8b, 0x8b, 0x65, 0x5c, 0x84, 0x35, 0x8f, 0x12, 0x9b, 0xea, 0xed, 0x62, 0xaa, 0x24,
	0x94, 0x73, 0xda, 0xf8, 0x53, 0xbe, 0x85, 0x9d, 0xd3, 0x16, 0xd6, 0xe9, 0x83, 0xf9, 0x3e, 0xa2,
	0x37, 0x21, 0x25, 0x31, 0xaa, 0xf4, 0x5a, 0x00, 0xe4, 0xcf, 0xc6, 0xa8, 0x9e, 0xc7, 0x6b, 0x1c,
	0x42, 0x86, 0xeb, 0xd4, 0xc6, 0x93, 0x61, 0x9e, 0x8d, 0x49, 0x07, 0x81, 0x75, 0x0b, 0xa1, 0xc9,
	0x94, 0x0c, 0xb3, 0x0a, 0x26, 0xe2, 0x25, 0x14, 0xae, 0x5d, 0xe3, 0xb3, 0xe5, 0x24, 0xbf, 0x17,
	0x60, 0x37, 0xb2, 0x2e, 0x27, 0x96, 0x85, 0xad, 0x0b, 0xc2, 0x9d, 0x1b, 0xc7, 0xd4, 0xb9, 0x43,
	0x5c, 0x74, 0x0a, 0xab, 0xc1, 0xbd, 0x17, 0x05, 0x9f, 0x74, 0xa9, 0xe5, 0x1b, 0x41, 0xd1, 0x31,
	0x6c, 0xda, 0x7a, 0x1b, 0x37, 0x75, 0xd3, 0x24, 0x9d, 0x45, 0x06, 0x27, 0x37, 0x0c, 0x3f, 0x09,
	0xa2, 0xeb, 0x16, 0x3a, 0x02, 0x08, 0x41, 0x53, 0x89, 0xd0, 0x8c, 0x3e, 0x86, 0xc9, 0x1f, 0x04,
	0x28, 0x45, 0x13, 0xc2, 0x6d, 0xd2, 0xfd, 0x82, 0x0a, 0xb4, 0x60, 0x37, 0xb2, 0x37, 0xf1, 0xeb,
	0xab, 0x85, 0xaa, 0x5b, 0x76, 0xe1, 0x47, 0x48, 0xf9, 0x06, 0x4a, 0x53, 0xdb, 0x19, 0xef, 0xe2,
	0x13, 0xe8, 0x54, 0xdf, 0xae, 0x02, 0xba, 0x66, 0x98, 0xfe, 0x15, 0xc4, 0x35, 0x82, 0x67, 0x0f,
	0x71, 0xc8, 0x4c, 0x1e, 0x07, 0xa4, 0x24, 0xf3, 0x4e, 0x3f, 0x55, 0x92, 0xba, 0x70, 0x7c, 0xf0,
	0xea, 0xc8, 0xab, 0xfd, 0x41, 0x45, 0x4c, 0x0b, 0xc8, 0x86, 0xfc, 0xb4, 0x8b, 0xa2, 0xa3, 0x64,
	0xb2, 0x19, 0xae, 0x2b, 0x15, 0xa2, 0xb0, 0x0b, 0x72, 0xa6, 0x73, 0x7d, 0x24, 0x04, 0xe8, 0x0e,
	0x50, 0xdc, 0x00, 0xd1, 0xcf, 0xc9, 0x52, 0x33, 0x2d, 0x33, 0x51, 0x2c, 0x8b, 0xfe, 0x83, 0x6c,
	0xc8, 0x02, 0xd1, 0xfe, 0x02, 0xb3, 0x1e, 0x71, 0xa6, 0x44, 0xfa, 0x02, 0xd2, 0x21, 0x17, 0xf1,
	0x33, 0x54, 0x4d, 0x16, 0x78, 0xc8, 0xfc, 0x12, 0x25, 0xb6, 0x90, 0x0d, 0x5b, 0xa1, 0xb4, 0x7e,
	0x23, 0xb4, 0x81, 0x19, 0x1b, 0x4e, 0xe0, 0xd3, 0xd6, 0x52, 0x1e, 0xb6, 0x2a, 0xf4, 0x5a, 0xcf,
	0xa3, 0x8f, 0x3f, 0xec, 0x89, 0xf4, 0x87, 0xd2, 0x1f, 0xfd, 0x41, 0x65, 0x63, 0x6f, 0x3d, 0xcc,
	0xd3, 0x1f, 0x54, 0x54, 0xf8, 0xc9, 0x70, 0x31, 0x9f, 0xa1, 0x13, 0x5f, 0x8e, 0xfb, 0x41, 0x45,
	0xcc, 0x0b, 0xd5, 0x77, 0x2b, 0xf0, 0x4d, 0xe8, 0xcf, 0x3f, 0x1d, 0xc6, 0xb1, 0x8b, 0x29, 0x7a,
	0x0e, 0x85, 0x4b, 0x37, 0x6e, 0xf0, 0xe8, 0xd7, 0x25, 0x3c, 0x2e, 0xe6, 0x29, 0xd2, 0xce, 0x54,
	0x61, 0x97, 0x4d, 0xed, 0xbc, 0x71, 0x75, 0x79, 0xd1, 0x38, 0x9f, 0x6c, 0xcf, 0x0b, 0xd8, 0x9e,
	0x12, 0x1e, 0x99, 0x06, 0x3a, 0x5e, 0xc6, 0x5e, 0xe3, 0x46, 0x33, 0x5f, 0x5c, 0x0c, 0xaa, 0x8e,
	0xfb, 0xe2, 0xbc, 0xaa, 0x93, 0x9d, 0x74, 0xbe, 0x70, 0x36, 0xa8, 0xfa, 0x21, 0xab, 0x9c, 0x57,
	0xf5, 0x3c, 0x7b, 0x9d, 0x2f, 0xbe, 0x2e, 0xfd, 0xd2, 0x1f, 0x54, 0x14, 0xf8, 0x71, 0xb1, 0xf1,
	0xf1, 0xc9, 0x7b, 0xf7, 0xfe, 0x65, 0xd5, 0x7e, 0xff, 0xb7, 0x66, 0x3b, 0xfc, 0xb6, 0x63, 0x28,
	0x26, 0x69, 0xab, 0xac, 0xe3, 0x61, 0xea, 0xed, 0xef, 0x73, 0xd5, 0x26, 0xde, 0x2d, 0xa6, 0x26,
	0xd5, 0x6f, 0xb8, 0x3a, 0xa4, 0x55, 0x0d, 0x9b, 0xa9, 0x63, 0x6a, 0x35, 0x4c, 0xad, 0x76, 0x0f,
	0x5e, 0x09, 0x5f, 0x7d, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x60, 0x1c, 0xbc, 0xb7, 0x0c, 0x00,
	0x00,
}
