// Code generated by protoc-gen-gcraft. DO NOT EDIT.
// source: user_manager_types.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	protocol "github.com/superp00t/gophercraft/bnet/bgs/protocol"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// BGSFieldOptions from public import global_extensions/field_options.proto
type BGSFieldOptions = protocol.BGSFieldOptions

// FieldRestriction from public import global_extensions/field_options.proto
type FieldRestriction = protocol.FieldRestriction
type FieldRestriction_Signed = protocol.FieldRestriction_Signed
type FieldRestriction_Unsigned = protocol.FieldRestriction_Unsigned
type FieldRestriction_Float = protocol.FieldRestriction_Float
type FieldRestriction_String_ = protocol.FieldRestriction_String_
type FieldRestriction_Repeated = protocol.FieldRestriction_Repeated
type FieldRestriction_Message = protocol.FieldRestriction_Message
type FieldRestriction_EntityId = protocol.FieldRestriction_EntityId
type FieldRestriction_Bytes = protocol.FieldRestriction_Bytes

// RepeatedFieldRestriction from public import global_extensions/field_options.proto
type RepeatedFieldRestriction = protocol.RepeatedFieldRestriction
type RepeatedFieldRestriction_Signed = protocol.RepeatedFieldRestriction_Signed
type RepeatedFieldRestriction_Unsigned = protocol.RepeatedFieldRestriction_Unsigned
type RepeatedFieldRestriction_Float = protocol.RepeatedFieldRestriction_Float
type RepeatedFieldRestriction_String_ = protocol.RepeatedFieldRestriction_String_
type RepeatedFieldRestriction_EntityId = protocol.RepeatedFieldRestriction_EntityId
type RepeatedFieldRestriction_Bytes = protocol.RepeatedFieldRestriction_Bytes

// SignedFieldRestriction from public import global_extensions/field_options.proto
type SignedFieldRestriction = protocol.SignedFieldRestriction

// UnsignedFieldRestriction from public import global_extensions/field_options.proto
type UnsignedFieldRestriction = protocol.UnsignedFieldRestriction

// FloatFieldRestriction from public import global_extensions/field_options.proto
type FloatFieldRestriction = protocol.FloatFieldRestriction

// StringFieldRestriction from public import global_extensions/field_options.proto
type StringFieldRestriction = protocol.StringFieldRestriction

// EntityIdRestriction from public import global_extensions/field_options.proto
type EntityIdRestriction = protocol.EntityIdRestriction

// MessageFieldRestriction from public import global_extensions/field_options.proto
type MessageFieldRestriction = protocol.MessageFieldRestriction

// LogOption from public import global_extensions/field_options.proto
type LogOption = protocol.LogOption

var LogOption_name = protocol.LogOption_name
var LogOption_value = protocol.LogOption_value

const LogOption_HIDDEN = LogOption(protocol.LogOption_HIDDEN)
const LogOption_HEX = LogOption(protocol.LogOption_HEX)

// EntityIdRestriction_Kind from public import global_extensions/field_options.proto
type EntityIdRestriction_Kind = protocol.EntityIdRestriction_Kind

var EntityIdRestriction_Kind_name = protocol.EntityIdRestriction_Kind_name
var EntityIdRestriction_Kind_value = protocol.EntityIdRestriction_Kind_value

const EntityIdRestriction_ANY = EntityIdRestriction_Kind(protocol.EntityIdRestriction_ANY)
const EntityIdRestriction_ACCOUNT = EntityIdRestriction_Kind(protocol.EntityIdRestriction_ACCOUNT)
const EntityIdRestriction_GAME_ACCOUNT = EntityIdRestriction_Kind(protocol.EntityIdRestriction_GAME_ACCOUNT)
const EntityIdRestriction_ACCOUNT_OR_GAME_ACCOUNT = EntityIdRestriction_Kind(protocol.EntityIdRestriction_ACCOUNT_OR_GAME_ACCOUNT)
const EntityIdRestriction_SERVICE = EntityIdRestriction_Kind(protocol.EntityIdRestriction_SERVICE)
const EntityIdRestriction_CHANNEL = EntityIdRestriction_Kind(protocol.EntityIdRestriction_CHANNEL)

var E_FieldOptions = protocol.E_FieldOptions

var E_Valid = protocol.E_Valid

type RecentPlayer struct {
	EntityId             *protocol.EntityId    `protobuf:"bytes,1,req,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	Program              *string               `protobuf:"bytes,2,opt,name=program" json:"program,omitempty"`
	TimestampPlayed      *uint64               `protobuf:"fixed64,3,opt,name=timestamp_played,json=timestampPlayed" json:"timestamp_played,omitempty"`
	Attributes           []*protocol.Attribute `protobuf:"bytes,4,rep,name=attributes" json:"attributes,omitempty"`
	Counter              *uint32               `protobuf:"fixed32,6,opt,name=counter,def=0" json:"counter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RecentPlayer) Reset()         { *m = RecentPlayer{} }
func (m *RecentPlayer) String() string { return proto.CompactTextString(m) }
func (*RecentPlayer) ProtoMessage()    {}
func (*RecentPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_2925132dac4de733, []int{0}
}

func (m *RecentPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecentPlayer.Unmarshal(m, b)
}
func (m *RecentPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecentPlayer.Marshal(b, m, deterministic)
}
func (m *RecentPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecentPlayer.Merge(m, src)
}
func (m *RecentPlayer) XXX_Size() int {
	return xxx_messageInfo_RecentPlayer.Size(m)
}
func (m *RecentPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_RecentPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_RecentPlayer proto.InternalMessageInfo

const Default_RecentPlayer_Counter uint32 = 0

func (m *RecentPlayer) GetEntityId() *protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *RecentPlayer) GetProgram() string {
	if m != nil && m.Program != nil {
		return *m.Program
	}
	return ""
}

func (m *RecentPlayer) GetTimestampPlayed() uint64 {
	if m != nil && m.TimestampPlayed != nil {
		return *m.TimestampPlayed
	}
	return 0
}

func (m *RecentPlayer) GetAttributes() []*protocol.Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *RecentPlayer) GetCounter() uint32 {
	if m != nil && m.Counter != nil {
		return *m.Counter
	}
	return Default_RecentPlayer_Counter
}

type BlockedPlayer struct {
	AccountId            *protocol.EntityId `protobuf:"bytes,1,req,name=account_id,json=accountId" json:"account_id,omitempty"`
	BattleTag            *string            `protobuf:"bytes,2,opt,name=battle_tag,json=battleTag" json:"battle_tag,omitempty"`
	Role                 []uint32           `protobuf:"varint,3,rep,name=role" json:"role,omitempty"`             // Deprecated: Do not use.
	Privileges           *uint64            `protobuf:"varint,4,opt,name=privileges" json:"privileges,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BlockedPlayer) Reset()         { *m = BlockedPlayer{} }
func (m *BlockedPlayer) String() string { return proto.CompactTextString(m) }
func (*BlockedPlayer) ProtoMessage()    {}
func (*BlockedPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_2925132dac4de733, []int{1}
}

func (m *BlockedPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockedPlayer.Unmarshal(m, b)
}
func (m *BlockedPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockedPlayer.Marshal(b, m, deterministic)
}
func (m *BlockedPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockedPlayer.Merge(m, src)
}
func (m *BlockedPlayer) XXX_Size() int {
	return xxx_messageInfo_BlockedPlayer.Size(m)
}
func (m *BlockedPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockedPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_BlockedPlayer proto.InternalMessageInfo

func (m *BlockedPlayer) GetAccountId() *protocol.EntityId {
	if m != nil {
		return m.AccountId
	}
	return nil
}

func (m *BlockedPlayer) GetBattleTag() string {
	if m != nil && m.BattleTag != nil {
		return *m.BattleTag
	}
	return ""
}

// Deprecated: Do not use.
func (m *BlockedPlayer) GetRole() []uint32 {
	if m != nil {
		return m.Role
	}
	return nil
}

// Deprecated: Do not use.
func (m *BlockedPlayer) GetPrivileges() uint64 {
	if m != nil && m.Privileges != nil {
		return *m.Privileges
	}
	return 0
}

func init() {
	proto.RegisterType((*RecentPlayer)(nil), "bgs.protocol.user_manager.v1.RecentPlayer")
	proto.RegisterType((*BlockedPlayer)(nil), "bgs.protocol.user_manager.v1.BlockedPlayer")
}

func init() { proto.RegisterFile("user_manager_types.proto", fileDescriptor_2925132dac4de733) }

var fileDescriptor_2925132dac4de733 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x6a, 0xdc, 0x30,
	0x10, 0xad, 0x76, 0x97, 0x6c, 0x77, 0xd2, 0xd0, 0x22, 0x68, 0x2a, 0xb6, 0x2d, 0x98, 0x85, 0x82,
	0x7b, 0xb1, 0x36, 0x29, 0xa5, 0xd0, 0x5b, 0x4d, 0x7b, 0xc8, 0x2d, 0x98, 0x9e, 0x7a, 0x31, 0xb2,
	0x3d, 0x51, 0x44, 0x65, 0x4b, 0x48, 0xe3, 0xa5, 0xfb, 0x39, 0xfd, 0xb1, 0x7e, 0x4b, 0x89, 0x63,
	0x07, 0xe7, 0x94, 0xdb, 0xcc, 0x7b, 0x6f, 0xf4, 0xde, 0x03, 0x81, 0xe8, 0x23, 0x86, 0xb2, 0x55,
	0x9d, 0xd2, 0x18, 0x4a, 0x3a, 0x7a, 0x8c, 0x99, 0x0f, 0x8e, 0x1c, 0x7f, 0x57, 0xe9, 0x71, 0xac,
	0x9d, 0xcd, 0xe6, 0xb2, 0xec, 0x70, 0xb1, 0xfd, 0xa0, 0xad, 0xab, 0x94, 0x2d, 0xf1, 0x0f, 0x61,
	0x17, 0x8d, 0xeb, 0xa2, 0xbc, 0x31, 0x68, 0x9b, 0xd2, 0x79, 0xba, 0xdb, 0xee, 0x2f, 0xb7, 0x1c,
	0x3b, 0x32, 0x74, 0x9c, 0x3f, 0xbc, 0x7d, 0xad, 0x88, 0x82, 0xa9, 0x7a, 0xc2, 0x39, 0xbc, 0xfb,
	0xc7, 0xe0, 0x45, 0x81, 0x35, 0x76, 0x74, 0x6d, 0xd5, 0x11, 0x03, 0xff, 0x04, 0x9b, 0xf1, 0xda,
	0x34, 0x82, 0x25, 0x8b, 0xf4, 0xf4, 0xf2, 0x3c, 0x7b, 0x14, 0xea, 0xc7, 0x40, 0x5f, 0x35, 0xc5,
	0x73, 0x1c, 0x27, 0x2e, 0x60, 0xed, 0x83, 0xd3, 0x41, 0xb5, 0x62, 0x91, 0xb0, 0x74, 0x53, 0x4c,
	0x2b, 0xff, 0x08, 0xaf, 0xc8, 0xb4, 0x18, 0x49, 0xb5, 0xbe, 0xf4, 0x77, 0x16, 0x8d, 0x58, 0x26,
	0x2c, 0x3d, 0x29, 0x5e, 0x3e, 0xe0, 0x83, 0x73, 0xc3, 0xbf, 0x00, 0x3c, 0x64, 0x8c, 0x62, 0x95,
	0x2c, 0xd3, 0xd3, 0xcb, 0x37, 0x8f, 0xad, 0xbf, 0x4d, 0x7c, 0x31, 0x93, 0xf2, 0xb7, 0xb0, 0xae,
	0x5d, 0xdf, 0x11, 0x06, 0x71, 0x92, 0xb0, 0x74, 0xfd, 0x95, 0xed, 0x8b, 0x09, 0xd9, 0xfd, 0x65,
	0x70, 0x96, 0x5b, 0x57, 0xff, 0xc6, 0x66, 0x6c, 0xf8, 0x19, 0x40, 0xd5, 0x03, 0xfd, 0x74, 0xc5,
	0xcd, 0xa8, 0xbc, 0x6a, 0xf8, 0x7b, 0x80, 0x4a, 0x11, 0x59, 0x2c, 0x49, 0xe9, 0xb1, 0xe6, 0xe6,
	0x1e, 0xf9, 0xa9, 0x34, 0x3f, 0x87, 0x55, 0x70, 0x16, 0xc5, 0x32, 0x59, 0xa6, 0x67, 0xf9, 0x42,
	0xb0, 0x62, 0xd8, 0xf9, 0x0e, 0xc0, 0x07, 0x73, 0x30, 0x16, 0xf5, 0xd0, 0x8a, 0xa5, 0xab, 0x81,
	0x9d, 0xa1, 0xf9, 0xf7, 0x5f, 0xb9, 0x36, 0x74, 0xdb, 0x57, 0x59, 0xed, 0x5a, 0x19, 0x7b, 0x8f,
	0xc1, 0xef, 0xf7, 0x24, 0xb5, 0xf3, 0xb7, 0x18, 0xea, 0xa0, 0x6e, 0x48, 0x56, 0x1d, 0x92, 0xac,
	0x74, 0x94, 0x53, 0x48, 0x39, 0xff, 0x1c, 0xf2, 0x70, 0x71, 0xfd, 0xec, 0x7f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x02, 0x18, 0xb9, 0x31, 0x57, 0x02, 0x00, 0x00,
}
