// Code generated by protoc-gen-gcraft. DO NOT EDIT.
// source: club_role.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	protocol "github.com/superp00t/gophercraft/bnet/bgs/protocol"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClubPrivilegeSet struct {
	CanDestroy                 *bool    `protobuf:"varint,1,opt,name=can_destroy,json=canDestroy" json:"can_destroy,omitempty"`
	CanSetAttribute            *bool    `protobuf:"varint,10,opt,name=can_set_attribute,json=canSetAttribute" json:"can_set_attribute,omitempty"`
	CanSetName                 *bool    `protobuf:"varint,11,opt,name=can_set_name,json=canSetName" json:"can_set_name,omitempty"`
	CanSetDescription          *bool    `protobuf:"varint,12,opt,name=can_set_description,json=canSetDescription" json:"can_set_description,omitempty"`
	CanSetAvatar               *bool    `protobuf:"varint,13,opt,name=can_set_avatar,json=canSetAvatar" json:"can_set_avatar,omitempty"`
	CanSetBroadcast            *bool    `protobuf:"varint,14,opt,name=can_set_broadcast,json=canSetBroadcast" json:"can_set_broadcast,omitempty"`
	CanSetPrivacyLevel         *bool    `protobuf:"varint,15,opt,name=can_set_privacy_level,json=canSetPrivacyLevel" json:"can_set_privacy_level,omitempty"`
	CanKickMember              *bool    `protobuf:"varint,30,opt,name=can_kick_member,json=canKickMember" json:"can_kick_member,omitempty"`
	CanSetOwnMemberAttribute   *bool    `protobuf:"varint,31,opt,name=can_set_own_member_attribute,json=canSetOwnMemberAttribute" json:"can_set_own_member_attribute,omitempty"`
	CanSetOtherMemberAttribute *bool    `protobuf:"varint,32,opt,name=can_set_other_member_attribute,json=canSetOtherMemberAttribute" json:"can_set_other_member_attribute,omitempty"`
	CanSetOwnVoiceState        *bool    `protobuf:"varint,33,opt,name=can_set_own_voice_state,json=canSetOwnVoiceState" json:"can_set_own_voice_state,omitempty"`
	CanSetOwnPresenceLevel     *bool    `protobuf:"varint,34,opt,name=can_set_own_presence_level,json=canSetOwnPresenceLevel" json:"can_set_own_presence_level,omitempty"`
	CanSetOwnWhisperLevel      *bool    `protobuf:"varint,35,opt,name=can_set_own_whisper_level,json=canSetOwnWhisperLevel" json:"can_set_own_whisper_level,omitempty"`
	CanSetOwnMemberNote        *bool    `protobuf:"varint,36,opt,name=can_set_own_member_note,json=canSetOwnMemberNote" json:"can_set_own_member_note,omitempty"`
	CanSetOtherMemberNote      *bool    `protobuf:"varint,37,opt,name=can_set_other_member_note,json=canSetOtherMemberNote" json:"can_set_other_member_note,omitempty"`
	CanUseVoice                *bool    `protobuf:"varint,50,opt,name=can_use_voice,json=canUseVoice" json:"can_use_voice,omitempty"`
	CanVoiceMuteMemberForAll   *bool    `protobuf:"varint,51,opt,name=can_voice_mute_member_for_all,json=canVoiceMuteMemberForAll" json:"can_voice_mute_member_for_all,omitempty"`
	CanGetInvitation           *bool    `protobuf:"varint,70,opt,name=can_get_invitation,json=canGetInvitation" json:"can_get_invitation,omitempty"`
	CanSendInvitation          *bool    `protobuf:"varint,71,opt,name=can_send_invitation,json=canSendInvitation" json:"can_send_invitation,omitempty"`
	CanSendGuestInvitation     *bool    `protobuf:"varint,72,opt,name=can_send_guest_invitation,json=canSendGuestInvitation" json:"can_send_guest_invitation,omitempty"`
	CanRevokeOwnInvitation     *bool    `protobuf:"varint,73,opt,name=can_revoke_own_invitation,json=canRevokeOwnInvitation" json:"can_revoke_own_invitation,omitempty"`
	CanRevokeOtherInvitation   *bool    `protobuf:"varint,74,opt,name=can_revoke_other_invitation,json=canRevokeOtherInvitation" json:"can_revoke_other_invitation,omitempty"`
	CanGetSuggestion           *bool    `protobuf:"varint,90,opt,name=can_get_suggestion,json=canGetSuggestion" json:"can_get_suggestion,omitempty"`
	CanSuggestMember           *bool    `protobuf:"varint,91,opt,name=can_suggest_member,json=canSuggestMember" json:"can_suggest_member,omitempty"`
	CanApproveMember           *bool    `protobuf:"varint,92,opt,name=can_approve_member,json=canApproveMember" json:"can_approve_member,omitempty"`
	CanGetTicket               *bool    `protobuf:"varint,110,opt,name=can_get_ticket,json=canGetTicket" json:"can_get_ticket,omitempty"`
	CanCreateTicket            *bool    `protobuf:"varint,111,opt,name=can_create_ticket,json=canCreateTicket" json:"can_create_ticket,omitempty"`
	CanDestroyTicket           *bool    `protobuf:"varint,112,opt,name=can_destroy_ticket,json=canDestroyTicket" json:"can_destroy_ticket,omitempty"`
	CanGetBan                  *bool    `protobuf:"varint,130,opt,name=can_get_ban,json=canGetBan" json:"can_get_ban,omitempty"`
	CanAddBan                  *bool    `protobuf:"varint,131,opt,name=can_add_ban,json=canAddBan" json:"can_add_ban,omitempty"`
	CanRemoveBan               *bool    `protobuf:"varint,132,opt,name=can_remove_ban,json=canRemoveBan" json:"can_remove_ban,omitempty"`
	CanCreateStream            *bool    `protobuf:"varint,140,opt,name=can_create_stream,json=canCreateStream" json:"can_create_stream,omitempty"`
	CanDestroyStream           *bool    `protobuf:"varint,141,opt,name=can_destroy_stream,json=canDestroyStream" json:"can_destroy_stream,omitempty"`
	CanSetStreamPosition       *bool    `protobuf:"varint,142,opt,name=can_set_stream_position,json=canSetStreamPosition" json:"can_set_stream_position,omitempty"`
	CanSetStreamAttribute      *bool    `protobuf:"varint,143,opt,name=can_set_stream_attribute,json=canSetStreamAttribute" json:"can_set_stream_attribute,omitempty"`
	CanSetStreamName           *bool    `protobuf:"varint,144,opt,name=can_set_stream_name,json=canSetStreamName" json:"can_set_stream_name,omitempty"`
	CanSetStreamSubject        *bool    `protobuf:"varint,145,opt,name=can_set_stream_subject,json=canSetStreamSubject" json:"can_set_stream_subject,omitempty"`
	CanSetStreamAccess         *bool    `protobuf:"varint,146,opt,name=can_set_stream_access,json=canSetStreamAccess" json:"can_set_stream_access,omitempty"`
	CanSetStreamVoiceLevel     *bool    `protobuf:"varint,147,opt,name=can_set_stream_voice_level,json=canSetStreamVoiceLevel" json:"can_set_stream_voice_level,omitempty"`
	CanCreateMessage           *bool    `protobuf:"varint,180,opt,name=can_create_message,json=canCreateMessage" json:"can_create_message,omitempty"`
	CanDestroyOwnMessage       *bool    `protobuf:"varint,181,opt,name=can_destroy_own_message,json=canDestroyOwnMessage" json:"can_destroy_own_message,omitempty"`
	CanDestroyOtherMessage     *bool    `protobuf:"varint,182,opt,name=can_destroy_other_message,json=canDestroyOtherMessage" json:"can_destroy_other_message,omitempty"`
	CanEditOwnMessage          *bool    `protobuf:"varint,183,opt,name=can_edit_own_message,json=canEditOwnMessage" json:"can_edit_own_message,omitempty"`
	CanPinMessage              *bool    `protobuf:"varint,184,opt,name=can_pin_message,json=canPinMessage" json:"can_pin_message,omitempty"`
	CanMentionAll              *bool    `protobuf:"varint,185,opt,name=can_mention_all,json=canMentionAll" json:"can_mention_all,omitempty"`
	CanMentionHere             *bool    `protobuf:"varint,186,opt,name=can_mention_here,json=canMentionHere" json:"can_mention_here,omitempty"`
	CanMentionMember           *bool    `protobuf:"varint,187,opt,name=can_mention_member,json=canMentionMember" json:"can_mention_member,omitempty"`
	CanMentionRole             *bool    `protobuf:"varint,188,opt,name=can_mention_role,json=canMentionRole" json:"can_mention_role,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *ClubPrivilegeSet) Reset()         { *m = ClubPrivilegeSet{} }
func (m *ClubPrivilegeSet) String() string { return proto.CompactTextString(m) }
func (*ClubPrivilegeSet) ProtoMessage()    {}
func (*ClubPrivilegeSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b7d7d234f84917f, []int{0}
}

func (m *ClubPrivilegeSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubPrivilegeSet.Unmarshal(m, b)
}
func (m *ClubPrivilegeSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubPrivilegeSet.Marshal(b, m, deterministic)
}
func (m *ClubPrivilegeSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubPrivilegeSet.Merge(m, src)
}
func (m *ClubPrivilegeSet) XXX_Size() int {
	return xxx_messageInfo_ClubPrivilegeSet.Size(m)
}
func (m *ClubPrivilegeSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubPrivilegeSet.DiscardUnknown(m)
}

var xxx_messageInfo_ClubPrivilegeSet proto.InternalMessageInfo

func (m *ClubPrivilegeSet) GetCanDestroy() bool {
	if m != nil && m.CanDestroy != nil {
		return *m.CanDestroy
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetAttribute() bool {
	if m != nil && m.CanSetAttribute != nil {
		return *m.CanSetAttribute
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetName() bool {
	if m != nil && m.CanSetName != nil {
		return *m.CanSetName
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetDescription() bool {
	if m != nil && m.CanSetDescription != nil {
		return *m.CanSetDescription
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetAvatar() bool {
	if m != nil && m.CanSetAvatar != nil {
		return *m.CanSetAvatar
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetBroadcast() bool {
	if m != nil && m.CanSetBroadcast != nil {
		return *m.CanSetBroadcast
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetPrivacyLevel() bool {
	if m != nil && m.CanSetPrivacyLevel != nil {
		return *m.CanSetPrivacyLevel
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanKickMember() bool {
	if m != nil && m.CanKickMember != nil {
		return *m.CanKickMember
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetOwnMemberAttribute() bool {
	if m != nil && m.CanSetOwnMemberAttribute != nil {
		return *m.CanSetOwnMemberAttribute
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetOtherMemberAttribute() bool {
	if m != nil && m.CanSetOtherMemberAttribute != nil {
		return *m.CanSetOtherMemberAttribute
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetOwnVoiceState() bool {
	if m != nil && m.CanSetOwnVoiceState != nil {
		return *m.CanSetOwnVoiceState
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetOwnPresenceLevel() bool {
	if m != nil && m.CanSetOwnPresenceLevel != nil {
		return *m.CanSetOwnPresenceLevel
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetOwnWhisperLevel() bool {
	if m != nil && m.CanSetOwnWhisperLevel != nil {
		return *m.CanSetOwnWhisperLevel
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetOwnMemberNote() bool {
	if m != nil && m.CanSetOwnMemberNote != nil {
		return *m.CanSetOwnMemberNote
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetOtherMemberNote() bool {
	if m != nil && m.CanSetOtherMemberNote != nil {
		return *m.CanSetOtherMemberNote
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanUseVoice() bool {
	if m != nil && m.CanUseVoice != nil {
		return *m.CanUseVoice
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanVoiceMuteMemberForAll() bool {
	if m != nil && m.CanVoiceMuteMemberForAll != nil {
		return *m.CanVoiceMuteMemberForAll
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanGetInvitation() bool {
	if m != nil && m.CanGetInvitation != nil {
		return *m.CanGetInvitation
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSendInvitation() bool {
	if m != nil && m.CanSendInvitation != nil {
		return *m.CanSendInvitation
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSendGuestInvitation() bool {
	if m != nil && m.CanSendGuestInvitation != nil {
		return *m.CanSendGuestInvitation
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanRevokeOwnInvitation() bool {
	if m != nil && m.CanRevokeOwnInvitation != nil {
		return *m.CanRevokeOwnInvitation
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanRevokeOtherInvitation() bool {
	if m != nil && m.CanRevokeOtherInvitation != nil {
		return *m.CanRevokeOtherInvitation
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanGetSuggestion() bool {
	if m != nil && m.CanGetSuggestion != nil {
		return *m.CanGetSuggestion
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSuggestMember() bool {
	if m != nil && m.CanSuggestMember != nil {
		return *m.CanSuggestMember
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanApproveMember() bool {
	if m != nil && m.CanApproveMember != nil {
		return *m.CanApproveMember
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanGetTicket() bool {
	if m != nil && m.CanGetTicket != nil {
		return *m.CanGetTicket
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanCreateTicket() bool {
	if m != nil && m.CanCreateTicket != nil {
		return *m.CanCreateTicket
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanDestroyTicket() bool {
	if m != nil && m.CanDestroyTicket != nil {
		return *m.CanDestroyTicket
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanGetBan() bool {
	if m != nil && m.CanGetBan != nil {
		return *m.CanGetBan
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanAddBan() bool {
	if m != nil && m.CanAddBan != nil {
		return *m.CanAddBan
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanRemoveBan() bool {
	if m != nil && m.CanRemoveBan != nil {
		return *m.CanRemoveBan
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanCreateStream() bool {
	if m != nil && m.CanCreateStream != nil {
		return *m.CanCreateStream
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanDestroyStream() bool {
	if m != nil && m.CanDestroyStream != nil {
		return *m.CanDestroyStream
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetStreamPosition() bool {
	if m != nil && m.CanSetStreamPosition != nil {
		return *m.CanSetStreamPosition
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetStreamAttribute() bool {
	if m != nil && m.CanSetStreamAttribute != nil {
		return *m.CanSetStreamAttribute
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetStreamName() bool {
	if m != nil && m.CanSetStreamName != nil {
		return *m.CanSetStreamName
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetStreamSubject() bool {
	if m != nil && m.CanSetStreamSubject != nil {
		return *m.CanSetStreamSubject
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetStreamAccess() bool {
	if m != nil && m.CanSetStreamAccess != nil {
		return *m.CanSetStreamAccess
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanSetStreamVoiceLevel() bool {
	if m != nil && m.CanSetStreamVoiceLevel != nil {
		return *m.CanSetStreamVoiceLevel
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanCreateMessage() bool {
	if m != nil && m.CanCreateMessage != nil {
		return *m.CanCreateMessage
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanDestroyOwnMessage() bool {
	if m != nil && m.CanDestroyOwnMessage != nil {
		return *m.CanDestroyOwnMessage
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanDestroyOtherMessage() bool {
	if m != nil && m.CanDestroyOtherMessage != nil {
		return *m.CanDestroyOtherMessage
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanEditOwnMessage() bool {
	if m != nil && m.CanEditOwnMessage != nil {
		return *m.CanEditOwnMessage
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanPinMessage() bool {
	if m != nil && m.CanPinMessage != nil {
		return *m.CanPinMessage
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanMentionAll() bool {
	if m != nil && m.CanMentionAll != nil {
		return *m.CanMentionAll
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanMentionHere() bool {
	if m != nil && m.CanMentionHere != nil {
		return *m.CanMentionHere
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanMentionMember() bool {
	if m != nil && m.CanMentionMember != nil {
		return *m.CanMentionMember
	}
	return false
}

func (m *ClubPrivilegeSet) GetCanMentionRole() bool {
	if m != nil && m.CanMentionRole != nil {
		return *m.CanMentionRole
	}
	return false
}

type ClubRole struct {
	Id                      *uint32             `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	State                   *protocol.RoleState `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	Privilege               *ClubPrivilegeSet   `protobuf:"bytes,3,opt,name=privilege" json:"privilege,omitempty"`
	AlwaysGrantStreamAccess *bool               `protobuf:"varint,4,opt,name=always_grant_stream_access,json=alwaysGrantStreamAccess" json:"always_grant_stream_access,omitempty"`
	AllowInClubSlot         *bool               `protobuf:"varint,5,opt,name=allow_in_club_slot,json=allowInClubSlot" json:"allow_in_club_slot,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}            `json:"-"`
	XXX_unrecognized        []byte              `json:"-"`
	XXX_sizecache           int32               `json:"-"`
}

func (m *ClubRole) Reset()         { *m = ClubRole{} }
func (m *ClubRole) String() string { return proto.CompactTextString(m) }
func (*ClubRole) ProtoMessage()    {}
func (*ClubRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b7d7d234f84917f, []int{1}
}

func (m *ClubRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubRole.Unmarshal(m, b)
}
func (m *ClubRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubRole.Marshal(b, m, deterministic)
}
func (m *ClubRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubRole.Merge(m, src)
}
func (m *ClubRole) XXX_Size() int {
	return xxx_messageInfo_ClubRole.Size(m)
}
func (m *ClubRole) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubRole.DiscardUnknown(m)
}

var xxx_messageInfo_ClubRole proto.InternalMessageInfo

func (m *ClubRole) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ClubRole) GetState() *protocol.RoleState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *ClubRole) GetPrivilege() *ClubPrivilegeSet {
	if m != nil {
		return m.Privilege
	}
	return nil
}

func (m *ClubRole) GetAlwaysGrantStreamAccess() bool {
	if m != nil && m.AlwaysGrantStreamAccess != nil {
		return *m.AlwaysGrantStreamAccess
	}
	return false
}

func (m *ClubRole) GetAllowInClubSlot() bool {
	if m != nil && m.AllowInClubSlot != nil {
		return *m.AllowInClubSlot
	}
	return false
}

type ClubRoleSet struct {
	Role                              []*ClubRole `protobuf:"bytes,1,rep,name=role" json:"role,omitempty"`
	DefaultRole                       []uint32    `protobuf:"varint,5,rep,packed,name=default_role,json=defaultRole" json:"default_role,omitempty"`
	AssignmentRespectsRelegationChain *bool       `protobuf:"varint,6,opt,name=assignment_respects_relegation_chain,json=assignmentRespectsRelegationChain" json:"assignment_respects_relegation_chain,omitempty"`
	Subtype                           *string     `protobuf:"bytes,7,opt,name=subtype" json:"subtype,omitempty"`
	XXX_NoUnkeyedLiteral              struct{}    `json:"-"`
	XXX_unrecognized                  []byte      `json:"-"`
	XXX_sizecache                     int32       `json:"-"`
}

func (m *ClubRoleSet) Reset()         { *m = ClubRoleSet{} }
func (m *ClubRoleSet) String() string { return proto.CompactTextString(m) }
func (*ClubRoleSet) ProtoMessage()    {}
func (*ClubRoleSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b7d7d234f84917f, []int{2}
}

func (m *ClubRoleSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubRoleSet.Unmarshal(m, b)
}
func (m *ClubRoleSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubRoleSet.Marshal(b, m, deterministic)
}
func (m *ClubRoleSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubRoleSet.Merge(m, src)
}
func (m *ClubRoleSet) XXX_Size() int {
	return xxx_messageInfo_ClubRoleSet.Size(m)
}
func (m *ClubRoleSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubRoleSet.DiscardUnknown(m)
}

var xxx_messageInfo_ClubRoleSet proto.InternalMessageInfo

func (m *ClubRoleSet) GetRole() []*ClubRole {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *ClubRoleSet) GetDefaultRole() []uint32 {
	if m != nil {
		return m.DefaultRole
	}
	return nil
}

func (m *ClubRoleSet) GetAssignmentRespectsRelegationChain() bool {
	if m != nil && m.AssignmentRespectsRelegationChain != nil {
		return *m.AssignmentRespectsRelegationChain
	}
	return false
}

func (m *ClubRoleSet) GetSubtype() string {
	if m != nil && m.Subtype != nil {
		return *m.Subtype
	}
	return ""
}

func init() {
	proto.RegisterType((*ClubPrivilegeSet)(nil), "bgs.protocol.club.v1.ClubPrivilegeSet")
	proto.RegisterType((*ClubRole)(nil), "bgs.protocol.club.v1.ClubRole")
	proto.RegisterType((*ClubRoleSet)(nil), "bgs.protocol.club.v1.ClubRoleSet")
}

func init() { proto.RegisterFile("club_role.proto", fileDescriptor_6b7d7d234f84917f) }

var fileDescriptor_6b7d7d234f84917f = []byte{
	// 1251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x96, 0x6b, 0x93, 0x14, 0x35,
	0x17, 0xc7, 0xab, 0x17, 0x78, 0x80, 0xec, 0x85, 0x25, 0xdc, 0xf2, 0xa0, 0xc2, 0xb0, 0x02, 0xae,
	0x22, 0x33, 0xb0, 0x52, 0x16, 0xe2, 0xad, 0x76, 0x41, 0x16, 0xd4, 0x85, 0xad, 0x1e, 0x2f, 0x55,
	0x68, 0x55, 0x57, 0xba, 0xfb, 0xd0, 0x13, 0xb7, 0x27, 0xdd, 0x95, 0xa4, 0x67, 0x6a, 0xdf, 0xaa,
	0x2f, 0xbd, 0xfb, 0x55, 0xbc, 0xa2, 0xdf, 0xc2, 0x4f, 0xe3, 0x3b, 0x2b, 0xb7, 0xee, 0xcc, 0xa0,
	0xef, 0x66, 0x72, 0x7e, 0xff, 0x9c, 0x9c, 0x93, 0xce, 0x3f, 0x41, 0xc7, 0xb2, 0xb2, 0x49, 0x13,
	0x51, 0x95, 0xd0, 0xaf, 0x45, 0xa5, 0x2a, 0x7c, 0x32, 0x2d, 0xa4, 0xfd, 0x99, 0x55, 0x65, 0x5f,
	0x47, 0xfb, 0x93, 0xeb, 0x67, 0x57, 0x35, 0x91, 0xa8, 0xfd, 0x1a, 0x5c, 0x70, 0xed, 0x09, 0x46,
	0xab, 0xb7, 0xcb, 0x26, 0xdd, 0x15, 0x6c, 0xc2, 0x4a, 0x28, 0x60, 0x08, 0x0a, 0x9f, 0x47, 0x8b,
	0x19, 0xe5, 0x49, 0x0e, 0x52, 0x89, 0x6a, 0x9f, 0x44, 0xbd, 0x68, 0xfd, 0x48, 0x8c, 0x32, 0xca,
	0xef, 0xd8, 0x11, 0xfc, 0x12, 0x3a, 0xae, 0x01, 0x09, 0x2a, 0xa1, 0x4a, 0x09, 0x96, 0x36, 0x0a,
	0x08, 0x32, 0xd8, 0xb1, 0x8c, 0xf2, 0x21, 0xa8, 0x4d, 0x3f, 0x8c, 0x7b, 0x68, 0xc9, 0xb3, 0x9c,
	0x8e, 0x81, 0x2c, 0xb6, 0xb3, 0x0d, 0x41, 0x3d, 0xa0, 0x63, 0xc0, 0x7d, 0x74, 0xc2, 0x13, 0x39,
	0xc8, 0x4c, 0xb0, 0x5a, 0xb1, 0x8a, 0x93, 0x25, 0x03, 0x1e, 0xb7, 0xe0, 0x9d, 0x2e, 0x80, 0x2f,
	0xa2, 0x95, 0x36, 0xfb, 0x84, 0x2a, 0x2a, 0xc8, 0xb2, 0x41, 0x97, 0x5c, 0x6a, 0x33, 0x16, 0xae,
	0x31, 0x15, 0x15, 0xcd, 0x33, 0x2a, 0x15, 0x59, 0x09, 0xd7, 0xb8, 0xe5, 0x87, 0xf1, 0x75, 0x74,
	0xca, 0xb3, 0xb5, 0x60, 0x13, 0x9a, 0xed, 0x27, 0x25, 0x4c, 0xa0, 0x24, 0xc7, 0x0c, 0x8f, 0x2d,
	0xbf, 0x6b, 0x43, 0xef, 0xeb, 0x08, 0xbe, 0x8c, 0xf4, 0x2c, 0xc9, 0x1e, 0xcb, 0xf6, 0x92, 0x31,
	0x8c, 0x53, 0x10, 0xe4, 0x9c, 0x81, 0x97, 0x33, 0xca, 0xdf, 0x63, 0xd9, 0xde, 0x8e, 0x19, 0xc4,
	0x6f, 0xa1, 0x67, 0xfd, 0xd4, 0xd5, 0x94, 0x3b, 0x34, 0xe8, 0xda, 0x79, 0x23, 0x22, 0x36, 0xc3,
	0xc3, 0x29, 0xb7, 0xb2, 0xae, 0x7d, 0x5b, 0xe8, 0x5c, 0xab, 0x57, 0x23, 0x10, 0x4f, 0xcf, 0xd0,
	0x33, 0x33, 0x9c, 0x75, 0x33, 0x68, 0x66, 0x7e, 0x8e, 0x1b, 0xe8, 0x4c, 0xb8, 0x86, 0x49, 0xc5,
	0x32, 0x48, 0xa4, 0xa2, 0x0a, 0xc8, 0x05, 0x23, 0x3e, 0xd1, 0xa6, 0xff, 0x48, 0xc7, 0x86, 0x3a,
	0x84, 0x6f, 0xa1, 0xb3, 0xa1, 0xaa, 0x16, 0x20, 0x81, 0x67, 0xe0, 0x3a, 0xb3, 0x66, 0x84, 0xa7,
	0x5b, 0xe1, 0xae, 0x0b, 0xdb, 0xee, 0xdc, 0x44, 0xff, 0x0f, 0xb5, 0xd3, 0x11, 0x93, 0x35, 0x08,
	0x27, 0x7d, 0xde, 0x48, 0x4f, 0xb5, 0xd2, 0x8f, 0x6d, 0xd4, 0x2a, 0xe7, 0xd6, 0xea, 0xaa, 0xe5,
	0x95, 0x02, 0x72, 0x71, 0x6e, 0xad, 0xb6, 0xcc, 0x07, 0x95, 0x82, 0x99, 0x7c, 0x61, 0x97, 0x8c,
	0xee, 0xd2, 0x4c, 0xbe, 0xae, 0x41, 0x46, 0xb9, 0x86, 0xf4, 0x86, 0x25, 0x8d, 0x04, 0xdb, 0x17,
	0xb2, 0x61, 0x68, 0x7d, 0x00, 0x3e, 0x94, 0x60, 0xda, 0x81, 0xdf, 0x46, 0xcf, 0x69, 0xc6, 0xf6,
	0x6d, 0xdc, 0x28, 0xf0, 0xd3, 0x3f, 0xae, 0x44, 0x42, 0xcb, 0x92, 0xbc, 0xd2, 0x6e, 0xa2, 0x11,
	0xec, 0x34, 0x0a, 0x6c, 0x8a, 0xbb, 0x95, 0xd8, 0x2c, 0x4b, 0xfc, 0x32, 0xd2, 0x9f, 0x50, 0x52,
	0x80, 0x4a, 0x18, 0x9f, 0x30, 0x45, 0xcd, 0x07, 0x7e, 0xd7, 0xa8, 0x56, 0x33, 0xca, 0xb7, 0x41,
	0xdd, 0x6f, 0xc7, 0xbb, 0xf3, 0xc0, 0xf3, 0x10, 0xdf, 0x0e, 0xce, 0x03, 0xcf, 0x03, 0xfe, 0x35,
	0x5f, 0x3c, 0xcf, 0x93, 0xa2, 0x01, 0x39, 0x93, 0xe4, 0x5e, 0xb0, 0x4f, 0x3c, 0xdf, 0xd6, 0xe1,
	0xa7, 0xa5, 0x02, 0x26, 0xd5, 0x1e, 0x98, 0x86, 0x07, 0xd2, 0xfb, 0xad, 0x34, 0x36, 0xf1, 0x87,
	0x53, 0x1e, 0x48, 0xdf, 0x44, 0xcf, 0x84, 0x52, 0xd3, 0xf5, 0x40, 0xfc, 0x6e, 0xdb, 0x12, 0x27,
	0xd6, 0x40, 0x20, 0x0f, 0x5a, 0x22, 0x9b, 0xa2, 0x00, 0x69, 0x54, 0x8f, 0xc2, 0x96, 0x0c, 0xdb,
	0x71, 0x4f, 0x3b, 0xd2, 0x1f, 0xb8, 0x4f, 0x5a, 0xda, 0xa1, 0xee, 0xcc, 0x39, 0x9a, 0xd6, 0xb5,
	0xa8, 0x26, 0x7e, 0xb3, 0xc8, 0xa7, 0x2d, 0xbd, 0x69, 0x03, 0x8e, 0x76, 0x76, 0xa2, 0x57, 0xa2,
	0x58, 0xb6, 0x07, 0x8a, 0xf0, 0xd6, 0x4e, 0xb6, 0x41, 0x7d, 0x60, 0xc6, 0xbc, 0x9d, 0x64, 0x02,
	0xa8, 0x02, 0x0f, 0x56, 0xad, 0x9d, 0xdc, 0x36, 0xe3, 0x8e, 0x75, 0xf9, 0x9d, 0x7f, 0x7a, 0xb8,
	0x6e, 0xf3, 0x3b, 0x1b, 0x75, 0xb4, 0x73, 0x5b, 0x9d, 0x3f, 0xa5, 0x9c, 0x7c, 0x6e, 0xed, 0xf6,
	0xa8, 0xcd, 0xbe, 0x45, 0xb9, 0x07, 0x68, 0x9e, 0x1b, 0xe0, 0x8b, 0x0e, 0xd8, 0xcc, 0x73, 0x0d,
	0x5c, 0xb2, 0x15, 0x08, 0x18, 0xeb, 0x72, 0x35, 0xf3, 0x65, 0xd4, 0x96, 0x10, 0x9b, 0x51, 0x8d,
	0x5d, 0x99, 0x29, 0x41, 0x2a, 0x01, 0x74, 0x4c, 0xbe, 0x8a, 0xe6, 0x6a, 0x18, 0x9a, 0x71, 0x7c,
	0x75, 0xb6, 0x06, 0x47, 0x7f, 0x1d, 0xcd, 0x17, 0xe1, 0xf0, 0x57, 0xbb, 0x63, 0x6b, 0xd1, 0xa4,
	0xae, 0x24, 0x33, 0x7b, 0xfa, 0x8d, 0xd5, 0x9c, 0xb4, 0xe7, 0xcf, 0xf2, 0xbb, 0x2e, 0x88, 0x6f,
	0x22, 0x32, 0xa7, 0xeb, 0x8c, 0xed, 0xdb, 0x28, 0x3c, 0xb8, 0x56, 0xd8, 0x99, 0x5a, 0x70, 0x6b,
	0x38, 0xa5, 0xb9, 0x5e, 0xbe, 0xeb, 0x56, 0xd8, 0x8a, 0xcc, 0x2d, 0x73, 0x03, 0x9d, 0x9e, 0xe3,
	0x65, 0x93, 0x7e, 0x06, 0x99, 0x22, 0xdf, 0x47, 0xa1, 0xb1, 0x58, 0xc9, 0xd0, 0xc6, 0xf0, 0x46,
	0x77, 0x33, 0xf8, 0xf5, 0x65, 0x19, 0x48, 0x49, 0x7e, 0x88, 0xc2, 0xab, 0xc1, 0x2d, 0xce, 0x84,
	0xf0, 0xeb, 0x9d, 0x71, 0x3a, 0x8d, 0x75, 0x0e, 0xeb, 0x7e, 0x3f, 0x46, 0xa1, 0x73, 0x5a, 0xa1,
	0x71, 0x0d, 0xeb, 0x7f, 0xae, 0xef, 0x6e, 0x93, 0xc6, 0x20, 0x25, 0x2d, 0x80, 0xfc, 0xd4, 0x55,
	0x65, 0x77, 0x69, 0xc7, 0x06, 0x7c, 0xdf, 0xfd, 0x36, 0x59, 0xcb, 0xb4, 0x9a, 0x9f, 0xbb, 0xbe,
	0xbb, 0xbd, 0x32, 0x9e, 0x69, 0x75, 0xb7, 0xec, 0xc1, 0x6f, 0x75, 0xce, 0x34, 0xad, 0xf2, 0x97,
	0x6e, 0x89, 0x5e, 0x69, 0x5d, 0xd3, 0x6a, 0xaf, 0x21, 0x3d, 0x67, 0x02, 0x39, 0x53, 0x33, 0x09,
	0x7f, 0x8d, 0x5a, 0x87, 0x7a, 0x27, 0x67, 0x2a, 0xc8, 0xf6, 0x82, 0xbd, 0x2c, 0x6b, 0xd6, 0xc1,
	0xbf, 0x45, 0xed, 0x6d, 0xb9, 0xcb, 0xe6, 0xc1, 0x31, 0x70, 0xfd, 0x75, 0x18, 0x6f, 0xfd, 0xbd,
	0x03, 0x77, 0xec, 0xb0, 0x76, 0xd4, 0x17, 0xd1, 0x6a, 0x08, 0x8e, 0x40, 0x00, 0x79, 0x62, 0xc9,
	0x95, 0x8e, 0xbc, 0x07, 0x02, 0x7c, 0x47, 0x3d, 0xea, 0xdc, 0xe0, 0x8f, 0xae, 0xa3, 0x0e, 0x76,
	0x76, 0x30, 0x37, 0xb3, 0x7e, 0x31, 0x91, 0x3f, 0x9f, 0x9a, 0x39, 0xae, 0x4a, 0x58, 0xfb, 0x3b,
	0x42, 0x47, 0xf4, 0xe3, 0x49, 0xff, 0xc1, 0x2b, 0x68, 0x81, 0xe5, 0xe6, 0xad, 0xb4, 0x1c, 0x2f,
	0xb0, 0x1c, 0x5f, 0x45, 0x87, 0xec, 0x15, 0xbb, 0xd0, 0x8b, 0xd6, 0x17, 0x37, 0xce, 0xf4, 0x67,
	0x5e, 0x64, 0x5a, 0x62, 0xae, 0xd9, 0xd8, 0x52, 0xf8, 0x0e, 0x3a, 0x5a, 0xfb, 0x37, 0x18, 0x39,
	0x60, 0x24, 0x97, 0xfb, 0xff, 0xf6, 0x88, 0xeb, 0xcf, 0x3f, 0xd7, 0xe2, 0x4e, 0xa8, 0x3f, 0x3d,
	0x5a, 0x4e, 0xe9, 0xbe, 0x4c, 0x0a, 0x41, 0xf9, 0xfc, 0x37, 0x7b, 0xd0, 0x54, 0x71, 0xc6, 0x12,
	0xdb, 0x1a, 0x98, 0xf9, 0x6e, 0xaf, 0x20, 0x4c, 0xcb, 0xb2, 0x9a, 0x26, 0x8c, 0x27, 0xe6, 0x3d,
	0x29, 0xcb, 0x4a, 0x91, 0x43, 0xd6, 0x1f, 0x4c, 0xe4, 0x3e, 0xd7, 0xc9, 0x87, 0x65, 0xa5, 0xd6,
	0xfe, 0x8a, 0xd0, 0xa2, 0xaf, 0x5d, 0xbf, 0x19, 0x37, 0xd0, 0x41, 0xd3, 0xaa, 0xa8, 0x77, 0x60,
	0x7d, 0x71, 0xe3, 0xdc, 0x7f, 0x2f, 0x5d, 0x0b, 0x62, 0xc3, 0xe2, 0x4b, 0x68, 0x29, 0x87, 0xc7,
	0xb4, 0x29, 0x95, 0x6d, 0xf3, 0xa1, 0xde, 0x81, 0xf5, 0xe5, 0xad, 0x85, 0xd5, 0x28, 0x5e, 0x74,
	0xe3, 0xa6, 0xb3, 0x0f, 0xd1, 0x45, 0x2a, 0x25, 0x2b, 0xb8, 0xde, 0x93, 0x44, 0x80, 0xac, 0x21,
	0x53, 0x32, 0x11, 0x50, 0x42, 0x61, 0x2e, 0x93, 0x24, 0x1b, 0x51, 0xc6, 0xc9, 0xff, 0xcc, 0x4a,
	0x2f, 0x74, 0x6c, 0xec, 0xd0, 0xb8, 0x25, 0x6f, 0x6b, 0x10, 0x13, 0x74, 0x58, 0x36, 0xa9, 0x7e,
	0x06, 0x93, 0xc3, 0xbd, 0x68, 0xfd, 0x68, 0xec, 0xff, 0x6e, 0xbd, 0xf1, 0xe8, 0x56, 0xc1, 0xd4,
	0xa8, 0x49, 0xfb, 0x59, 0x35, 0x1e, 0xc8, 0xa6, 0x06, 0x51, 0x5f, 0xbb, 0xa6, 0x06, 0x45, 0x55,
	0x8f, 0x40, 0x64, 0x82, 0x3e, 0x56, 0x83, 0x94, 0x83, 0x1a, 0xa4, 0x85, 0x1c, 0xf8, 0xf2, 0x06,
	0xba, 0xbc, 0xc1, 0xe4, 0xfa, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x67, 0xc2, 0xf3, 0x86,
	0x0b, 0x00, 0x00,
}
