// Code generated by protoc-gen-gcraft. DO NOT EDIT.
// source: club_enum.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrivacyLevel int32

const (
	PrivacyLevel_PRIVACY_LEVEL_CLOSED          PrivacyLevel = 0
	PrivacyLevel_PRIVACY_LEVEL_OPEN_INVITATION PrivacyLevel = 1
	PrivacyLevel_PRIVACY_LEVEL_OPEN_TICKET     PrivacyLevel = 2
	PrivacyLevel_PRIVACY_LEVEL_OPEN            PrivacyLevel = 3
)

var PrivacyLevel_name = map[int32]string{
	0: "PRIVACY_LEVEL_CLOSED",
	1: "PRIVACY_LEVEL_OPEN_INVITATION",
	2: "PRIVACY_LEVEL_OPEN_TICKET",
	3: "PRIVACY_LEVEL_OPEN",
}

var PrivacyLevel_value = map[string]int32{
	"PRIVACY_LEVEL_CLOSED":          0,
	"PRIVACY_LEVEL_OPEN_INVITATION": 1,
	"PRIVACY_LEVEL_OPEN_TICKET":     2,
	"PRIVACY_LEVEL_OPEN":            3,
}

func (x PrivacyLevel) Enum() *PrivacyLevel {
	p := new(PrivacyLevel)
	*p = x
	return p
}

func (x PrivacyLevel) String() string {
	return proto.EnumName(PrivacyLevel_name, int32(x))
}

func (x *PrivacyLevel) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PrivacyLevel_value, data, "PrivacyLevel")
	if err != nil {
		return err
	}
	*x = PrivacyLevel(value)
	return nil
}

func (PrivacyLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4fe921c60b1adc1b, []int{0}
}

type VisibilityLevel int32

const (
	VisibilityLevel_VISIBILITY_LEVEL_PRIVATE VisibilityLevel = 0
	VisibilityLevel_VISIBILITY_LEVEL_PUBLIC  VisibilityLevel = 1
)

var VisibilityLevel_name = map[int32]string{
	0: "VISIBILITY_LEVEL_PRIVATE",
	1: "VISIBILITY_LEVEL_PUBLIC",
}

var VisibilityLevel_value = map[string]int32{
	"VISIBILITY_LEVEL_PRIVATE": 0,
	"VISIBILITY_LEVEL_PUBLIC":  1,
}

func (x VisibilityLevel) Enum() *VisibilityLevel {
	p := new(VisibilityLevel)
	*p = x
	return p
}

func (x VisibilityLevel) String() string {
	return proto.EnumName(VisibilityLevel_name, int32(x))
}

func (x *VisibilityLevel) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(VisibilityLevel_value, data, "VisibilityLevel")
	if err != nil {
		return err
	}
	*x = VisibilityLevel(value)
	return nil
}

func (VisibilityLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4fe921c60b1adc1b, []int{1}
}

type ClubRemovedReason int32

const (
	ClubRemovedReason_CLUB_REMOVED_REASON_NONE                      ClubRemovedReason = 0
	ClubRemovedReason_CLUB_REMOVED_REASON_MEMBER_LEFT               ClubRemovedReason = 1
	ClubRemovedReason_CLUB_REMOVED_REASON_MEMBER_KICKED             ClubRemovedReason = 2
	ClubRemovedReason_CLUB_REMOVED_REASON_MEMBER_BANNED             ClubRemovedReason = 3
	ClubRemovedReason_CLUB_REMOVED_REASON_MEMBER_REMOVED_BY_SERVICE ClubRemovedReason = 4
	ClubRemovedReason_CLUB_REMOVED_REASON_DESTROYED_BY_MEMBER       ClubRemovedReason = 5
	ClubRemovedReason_CLUB_REMOVED_REASON_DESTROYED_BY_SERVICE      ClubRemovedReason = 6
)

var ClubRemovedReason_name = map[int32]string{
	0: "CLUB_REMOVED_REASON_NONE",
	1: "CLUB_REMOVED_REASON_MEMBER_LEFT",
	2: "CLUB_REMOVED_REASON_MEMBER_KICKED",
	3: "CLUB_REMOVED_REASON_MEMBER_BANNED",
	4: "CLUB_REMOVED_REASON_MEMBER_REMOVED_BY_SERVICE",
	5: "CLUB_REMOVED_REASON_DESTROYED_BY_MEMBER",
	6: "CLUB_REMOVED_REASON_DESTROYED_BY_SERVICE",
}

var ClubRemovedReason_value = map[string]int32{
	"CLUB_REMOVED_REASON_NONE":                      0,
	"CLUB_REMOVED_REASON_MEMBER_LEFT":               1,
	"CLUB_REMOVED_REASON_MEMBER_KICKED":             2,
	"CLUB_REMOVED_REASON_MEMBER_BANNED":             3,
	"CLUB_REMOVED_REASON_MEMBER_REMOVED_BY_SERVICE": 4,
	"CLUB_REMOVED_REASON_DESTROYED_BY_MEMBER":       5,
	"CLUB_REMOVED_REASON_DESTROYED_BY_SERVICE":      6,
}

func (x ClubRemovedReason) Enum() *ClubRemovedReason {
	p := new(ClubRemovedReason)
	*p = x
	return p
}

func (x ClubRemovedReason) String() string {
	return proto.EnumName(ClubRemovedReason_name, int32(x))
}

func (x *ClubRemovedReason) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClubRemovedReason_value, data, "ClubRemovedReason")
	if err != nil {
		return err
	}
	*x = ClubRemovedReason(value)
	return nil
}

func (ClubRemovedReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4fe921c60b1adc1b, []int{2}
}

type StreamVoiceLevel int32

const (
	StreamVoiceLevel_VOICE_LEVEL_DISABLED     StreamVoiceLevel = 0
	StreamVoiceLevel_VOICE_LEVEL_PUSH_TO_TALK StreamVoiceLevel = 1
	StreamVoiceLevel_VOICE_LEVEL_OPEN_MIC     StreamVoiceLevel = 2
)

var StreamVoiceLevel_name = map[int32]string{
	0: "VOICE_LEVEL_DISABLED",
	1: "VOICE_LEVEL_PUSH_TO_TALK",
	2: "VOICE_LEVEL_OPEN_MIC",
}

var StreamVoiceLevel_value = map[string]int32{
	"VOICE_LEVEL_DISABLED":     0,
	"VOICE_LEVEL_PUSH_TO_TALK": 1,
	"VOICE_LEVEL_OPEN_MIC":     2,
}

func (x StreamVoiceLevel) Enum() *StreamVoiceLevel {
	p := new(StreamVoiceLevel)
	*p = x
	return p
}

func (x StreamVoiceLevel) String() string {
	return proto.EnumName(StreamVoiceLevel_name, int32(x))
}

func (x *StreamVoiceLevel) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StreamVoiceLevel_value, data, "StreamVoiceLevel")
	if err != nil {
		return err
	}
	*x = StreamVoiceLevel(value)
	return nil
}

func (StreamVoiceLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4fe921c60b1adc1b, []int{3}
}

type VoiceMicrophoneState int32

const (
	VoiceMicrophoneState_MICROPHONE_STATE_NORMAL    VoiceMicrophoneState = 0
	VoiceMicrophoneState_MICROPHONE_STATE_SELF_MUTE VoiceMicrophoneState = 1
	VoiceMicrophoneState_MICROPHONE_STATE_SELF_DEAF VoiceMicrophoneState = 2
)

var VoiceMicrophoneState_name = map[int32]string{
	0: "MICROPHONE_STATE_NORMAL",
	1: "MICROPHONE_STATE_SELF_MUTE",
	2: "MICROPHONE_STATE_SELF_DEAF",
}

var VoiceMicrophoneState_value = map[string]int32{
	"MICROPHONE_STATE_NORMAL":    0,
	"MICROPHONE_STATE_SELF_MUTE": 1,
	"MICROPHONE_STATE_SELF_DEAF": 2,
}

func (x VoiceMicrophoneState) Enum() *VoiceMicrophoneState {
	p := new(VoiceMicrophoneState)
	*p = x
	return p
}

func (x VoiceMicrophoneState) String() string {
	return proto.EnumName(VoiceMicrophoneState_name, int32(x))
}

func (x *VoiceMicrophoneState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(VoiceMicrophoneState_value, data, "VoiceMicrophoneState")
	if err != nil {
		return err
	}
	*x = VoiceMicrophoneState(value)
	return nil
}

func (VoiceMicrophoneState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4fe921c60b1adc1b, []int{4}
}

type PresenceLevel int32

const (
	PresenceLevel_PRESENCE_LEVEL_NONE  PresenceLevel = 0
	PresenceLevel_PRESENCE_LEVEL_BASIC PresenceLevel = 1
	PresenceLevel_PRESENCE_LEVEL_RICH  PresenceLevel = 2
)

var PresenceLevel_name = map[int32]string{
	0: "PRESENCE_LEVEL_NONE",
	1: "PRESENCE_LEVEL_BASIC",
	2: "PRESENCE_LEVEL_RICH",
}

var PresenceLevel_value = map[string]int32{
	"PRESENCE_LEVEL_NONE":  0,
	"PRESENCE_LEVEL_BASIC": 1,
	"PRESENCE_LEVEL_RICH":  2,
}

func (x PresenceLevel) Enum() *PresenceLevel {
	p := new(PresenceLevel)
	*p = x
	return p
}

func (x PresenceLevel) String() string {
	return proto.EnumName(PresenceLevel_name, int32(x))
}

func (x *PresenceLevel) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PresenceLevel_value, data, "PresenceLevel")
	if err != nil {
		return err
	}
	*x = PresenceLevel(value)
	return nil
}

func (PresenceLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4fe921c60b1adc1b, []int{5}
}

type WhisperLevel int32

const (
	WhisperLevel_WHISPER_LEVEL_OPEN       WhisperLevel = 0
	WhisperLevel_WHISPER_LEVEL_RESTRICTED WhisperLevel = 1
)

var WhisperLevel_name = map[int32]string{
	0: "WHISPER_LEVEL_OPEN",
	1: "WHISPER_LEVEL_RESTRICTED",
}

var WhisperLevel_value = map[string]int32{
	"WHISPER_LEVEL_OPEN":       0,
	"WHISPER_LEVEL_RESTRICTED": 1,
}

func (x WhisperLevel) Enum() *WhisperLevel {
	p := new(WhisperLevel)
	*p = x
	return p
}

func (x WhisperLevel) String() string {
	return proto.EnumName(WhisperLevel_name, int32(x))
}

func (x *WhisperLevel) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(WhisperLevel_value, data, "WhisperLevel")
	if err != nil {
		return err
	}
	*x = WhisperLevel(value)
	return nil
}

func (WhisperLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4fe921c60b1adc1b, []int{6}
}

type StreamNotificationFilter int32

const (
	StreamNotificationFilter_STREAM_NOTIFICATION_FILTER_NONE    StreamNotificationFilter = 0
	StreamNotificationFilter_STREAM_NOTIFICATION_FILTER_MENTION StreamNotificationFilter = 1
	StreamNotificationFilter_STREAM_NOTIFICATION_FILTER_ALL     StreamNotificationFilter = 2
)

var StreamNotificationFilter_name = map[int32]string{
	0: "STREAM_NOTIFICATION_FILTER_NONE",
	1: "STREAM_NOTIFICATION_FILTER_MENTION",
	2: "STREAM_NOTIFICATION_FILTER_ALL",
}

var StreamNotificationFilter_value = map[string]int32{
	"STREAM_NOTIFICATION_FILTER_NONE":    0,
	"STREAM_NOTIFICATION_FILTER_MENTION": 1,
	"STREAM_NOTIFICATION_FILTER_ALL":     2,
}

func (x StreamNotificationFilter) Enum() *StreamNotificationFilter {
	p := new(StreamNotificationFilter)
	*p = x
	return p
}

func (x StreamNotificationFilter) String() string {
	return proto.EnumName(StreamNotificationFilter_name, int32(x))
}

func (x *StreamNotificationFilter) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StreamNotificationFilter_value, data, "StreamNotificationFilter")
	if err != nil {
		return err
	}
	*x = StreamNotificationFilter(value)
	return nil
}

func (StreamNotificationFilter) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4fe921c60b1adc1b, []int{7}
}

func init() {
	proto.RegisterEnum("bgs.protocol.club.v1.PrivacyLevel", PrivacyLevel_name, PrivacyLevel_value)
	proto.RegisterEnum("bgs.protocol.club.v1.VisibilityLevel", VisibilityLevel_name, VisibilityLevel_value)
	proto.RegisterEnum("bgs.protocol.club.v1.ClubRemovedReason", ClubRemovedReason_name, ClubRemovedReason_value)
	proto.RegisterEnum("bgs.protocol.club.v1.StreamVoiceLevel", StreamVoiceLevel_name, StreamVoiceLevel_value)
	proto.RegisterEnum("bgs.protocol.club.v1.VoiceMicrophoneState", VoiceMicrophoneState_name, VoiceMicrophoneState_value)
	proto.RegisterEnum("bgs.protocol.club.v1.PresenceLevel", PresenceLevel_name, PresenceLevel_value)
	proto.RegisterEnum("bgs.protocol.club.v1.WhisperLevel", WhisperLevel_name, WhisperLevel_value)
	proto.RegisterEnum("bgs.protocol.club.v1.StreamNotificationFilter", StreamNotificationFilter_name, StreamNotificationFilter_value)
}

func init() { proto.RegisterFile("club_enum.proto", fileDescriptor_4fe921c60b1adc1b) }

var fileDescriptor_4fe921c60b1adc1b = []byte{
	// 608 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x5b, 0x6f, 0xd3, 0x3e,
	0x14, 0x5f, 0xba, 0xff, 0x9f, 0x07, 0x6b, 0x68, 0x26, 0x4c, 0xdb, 0xb8, 0x6c, 0x68, 0x43, 0x5c,
	0x14, 0xa0, 0xd9, 0x5e, 0x11, 0x2f, 0xb9, 0x9c, 0xaa, 0xd6, 0x1c, 0x27, 0xb2, 0xdd, 0x4c, 0x83,
	0x07, 0xab, 0xc9, 0xbc, 0x36, 0x52, 0xdb, 0x54, 0x49, 0x5a, 0x89, 0x57, 0x5e, 0xf9, 0x36, 0x7c,
	0x42, 0x94, 0xb4, 0x9d, 0x18, 0x2b, 0xdd, 0x9b, 0xe5, 0xdf, 0x45, 0xc7, 0xe7, 0xfc, 0x7c, 0xd0,
	0x6e, 0x3a, 0x9a, 0x25, 0x4a, 0x4f, 0x66, 0xe3, 0xf6, 0xb4, 0xc8, 0xab, 0xdc, 0xdc, 0x4b, 0x06,
	0xe5, 0xe2, 0x98, 0xe6, 0xa3, 0x76, 0x8d, 0xb6, 0xe7, 0xe7, 0xd6, 0x0f, 0x03, 0xed, 0x44, 0x45,
	0x36, 0xef, 0xa7, 0xdf, 0xa9, 0x9e, 0xeb, 0x91, 0x79, 0x88, 0xf6, 0x22, 0x4e, 0x62, 0xc7, 0xbb,
	0x52, 0x14, 0x62, 0xa0, 0xca, 0xa3, 0xa1, 0x00, 0x1f, 0x6f, 0x99, 0x27, 0xe8, 0xe8, 0x2e, 0x12,
	0x46, 0xc0, 0x14, 0x61, 0x31, 0x91, 0x8e, 0x24, 0x21, 0xc3, 0x86, 0x79, 0x84, 0x9e, 0xad, 0xa1,
	0x48, 0xe2, 0x5d, 0x80, 0xc4, 0x2d, 0x73, 0x1f, 0x99, 0xf7, 0x61, 0xbc, 0x6d, 0x51, 0xb4, 0x1b,
	0x67, 0x65, 0x96, 0x64, 0xa3, 0xac, 0x5a, 0x96, 0xf1, 0x12, 0x1d, 0xc6, 0x44, 0x10, 0x97, 0x50,
	0x22, 0x57, 0xec, 0x46, 0x2b, 0x01, 0x6f, 0x99, 0x2f, 0xd0, 0xc1, 0x7d, 0xb4, 0xe7, 0x52, 0xe2,
	0x61, 0xc3, 0xfa, 0xd5, 0x42, 0x4f, 0xbc, 0xd1, 0x2c, 0xe1, 0x7a, 0x9c, 0xcf, 0xf5, 0x35, 0xd7,
	0xfd, 0x32, 0x9f, 0xd4, 0x86, 0x1e, 0xed, 0xb9, 0x8a, 0x43, 0x10, 0xc6, 0xe0, 0x2b, 0x0e, 0x8e,
	0x08, 0x99, 0x62, 0x21, 0xab, 0x0d, 0x5f, 0xa3, 0x57, 0xeb, 0xd0, 0x00, 0x02, 0x17, 0xb8, 0xa2,
	0xd0, 0x91, 0xd8, 0x30, 0xdf, 0xa0, 0x93, 0x0d, 0xa4, 0x8b, 0xfa, 0x95, 0x3e, 0x6e, 0x3d, 0x40,
	0x73, 0x1d, 0xc6, 0xc0, 0xc7, 0xdb, 0xe6, 0x39, 0xfa, 0xb4, 0x81, 0xb6, 0xba, 0x75, 0xaf, 0x94,
	0x00, 0x1e, 0x13, 0x0f, 0xf0, 0x7f, 0xe6, 0x07, 0xf4, 0x6e, 0x9d, 0xc4, 0x07, 0x21, 0x79, 0x78,
	0xb5, 0x60, 0x2f, 0xf4, 0xf8, 0x7f, 0xf3, 0x23, 0x7a, 0xff, 0x20, 0x79, 0x65, 0xfd, 0xc8, 0xba,
	0x46, 0x58, 0x54, 0x85, 0xee, 0x8f, 0xe3, 0x3c, 0x4b, 0xf5, 0x6d, 0x14, 0xe2, 0x90, 0x78, 0xb0,
	0x6c, 0xb0, 0x4f, 0x84, 0xe3, 0xd2, 0x26, 0x0a, 0xf5, 0x74, 0xfe, 0x40, 0xa2, 0x9e, 0xe8, 0x2a,
	0x19, 0x2a, 0xe9, 0xd0, 0x0b, 0x6c, 0xfc, 0xad, 0x6b, 0x32, 0x10, 0x10, 0x0f, 0xb7, 0xac, 0x12,
	0xed, 0x35, 0xfe, 0x41, 0x96, 0x16, 0xf9, 0x74, 0x98, 0x4f, 0xb4, 0xa8, 0xfa, 0x95, 0xae, 0xe7,
	0x19, 0x10, 0x8f, 0x87, 0x51, 0x37, 0x64, 0xa0, 0x84, 0x74, 0x24, 0x28, 0x16, 0xf2, 0xc0, 0xa1,
	0x78, 0xcb, 0x3c, 0x46, 0xcf, 0xef, 0x81, 0x02, 0x68, 0x47, 0x05, 0x3d, 0x09, 0xd8, 0xf8, 0x37,
	0xee, 0x83, 0xd3, 0xc1, 0x2d, 0xeb, 0x1b, 0x7a, 0x1c, 0x15, 0xba, 0xd4, 0x93, 0xd5, 0xbb, 0x0e,
	0xd0, 0xd3, 0x88, 0x83, 0x00, 0x76, 0x5b, 0xe2, 0x32, 0x05, 0x4d, 0xf6, 0xef, 0x00, 0xae, 0x23,
	0xea, 0x4c, 0xad, 0x91, 0x70, 0xe2, 0x75, 0x71, 0xcb, 0xf2, 0xd1, 0xce, 0xe5, 0x30, 0x2b, 0xa7,
	0xba, 0x58, 0x78, 0xef, 0x23, 0xf3, 0xb2, 0x4b, 0x44, 0xd4, 0xa4, 0xe6, 0x36, 0xe2, 0x4d, 0xc7,
	0xee, 0xde, 0xf3, 0x7a, 0x0e, 0xc4, 0x93, 0xe0, 0x63, 0xc3, 0xfa, 0x69, 0xa0, 0xc3, 0x45, 0xfb,
	0x59, 0x5e, 0x65, 0x37, 0x59, 0xda, 0xaf, 0xb2, 0x7c, 0xd2, 0xc9, 0x46, 0x95, 0x2e, 0xea, 0x6c,
	0x0a, 0xc9, 0xc1, 0x09, 0x14, 0x0b, 0x25, 0xe9, 0x10, 0xaf, 0xf9, 0x6d, 0xaa, 0x43, 0xa8, 0x04,
	0xbe, 0x2a, 0xfd, 0x2d, 0x3a, 0xdd, 0x40, 0x0a, 0x80, 0x2d, 0x7f, 0xe8, 0x29, 0x3a, 0xde, 0xc0,
	0x73, 0x28, 0xc5, 0x2d, 0xf7, 0xcb, 0xd7, 0xcf, 0x83, 0xac, 0x1a, 0xce, 0x92, 0x76, 0x9a, 0x8f,
	0xed, 0x72, 0x36, 0xd5, 0xc5, 0xf4, 0xec, 0xac, 0xb2, 0x07, 0xf9, 0x74, 0xa8, 0x8b, 0xb4, 0xe8,
	0xdf, 0x54, 0x76, 0x32, 0xd1, 0x95, 0x9d, 0x0c, 0x4a, 0x7b, 0xb5, 0x51, 0xec, 0x7a, 0xa3, 0xd8,
	0xf3, 0xf3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x1b, 0x01, 0x3e, 0x79, 0x04, 0x00, 0x00,
}
