// Code generated by protoc-gen-gcraft. DO NOT EDIT.
// source: club_range_set.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	protocol "github.com/superp00t/gophercraft/bnet/bgs/protocol"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClubTypeRangeSet struct {
	NameRange            *protocol.UnsignedIntRange `protobuf:"bytes,2,opt,name=name_range,json=nameRange" json:"name_range,omitempty"`
	DescriptionRange     *protocol.UnsignedIntRange `protobuf:"bytes,3,opt,name=description_range,json=descriptionRange" json:"description_range,omitempty"`
	BroadcastRange       *protocol.UnsignedIntRange `protobuf:"bytes,4,opt,name=broadcast_range,json=broadcastRange" json:"broadcast_range,omitempty"`
	ShortNameRange       *protocol.UnsignedIntRange `protobuf:"bytes,7,opt,name=short_name_range,json=shortNameRange" json:"short_name_range,omitempty"`
	Member               *ClubMemberRangeSet        `protobuf:"bytes,25,opt,name=member" json:"member,omitempty"`
	Stream               *ClubStreamRangeSet        `protobuf:"bytes,26,opt,name=stream" json:"stream,omitempty"`
	Invitation           *ClubInvitationRangeSet    `protobuf:"bytes,27,opt,name=invitation" json:"invitation,omitempty"`
	Suggestion           *ClubSuggestionRangeSet    `protobuf:"bytes,28,opt,name=suggestion" json:"suggestion,omitempty"`
	Ticket               *ClubTicketRangeSet        `protobuf:"bytes,29,opt,name=ticket" json:"ticket,omitempty"`
	Ban                  *ClubBanRangeSet           `protobuf:"bytes,30,opt,name=ban" json:"ban,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ClubTypeRangeSet) Reset()         { *m = ClubTypeRangeSet{} }
func (m *ClubTypeRangeSet) String() string { return proto.CompactTextString(m) }
func (*ClubTypeRangeSet) ProtoMessage()    {}
func (*ClubTypeRangeSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_a06cd3d74328deaa, []int{0}
}

func (m *ClubTypeRangeSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubTypeRangeSet.Unmarshal(m, b)
}
func (m *ClubTypeRangeSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubTypeRangeSet.Marshal(b, m, deterministic)
}
func (m *ClubTypeRangeSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubTypeRangeSet.Merge(m, src)
}
func (m *ClubTypeRangeSet) XXX_Size() int {
	return xxx_messageInfo_ClubTypeRangeSet.Size(m)
}
func (m *ClubTypeRangeSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubTypeRangeSet.DiscardUnknown(m)
}

var xxx_messageInfo_ClubTypeRangeSet proto.InternalMessageInfo

func (m *ClubTypeRangeSet) GetNameRange() *protocol.UnsignedIntRange {
	if m != nil {
		return m.NameRange
	}
	return nil
}

func (m *ClubTypeRangeSet) GetDescriptionRange() *protocol.UnsignedIntRange {
	if m != nil {
		return m.DescriptionRange
	}
	return nil
}

func (m *ClubTypeRangeSet) GetBroadcastRange() *protocol.UnsignedIntRange {
	if m != nil {
		return m.BroadcastRange
	}
	return nil
}

func (m *ClubTypeRangeSet) GetShortNameRange() *protocol.UnsignedIntRange {
	if m != nil {
		return m.ShortNameRange
	}
	return nil
}

func (m *ClubTypeRangeSet) GetMember() *ClubMemberRangeSet {
	if m != nil {
		return m.Member
	}
	return nil
}

func (m *ClubTypeRangeSet) GetStream() *ClubStreamRangeSet {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (m *ClubTypeRangeSet) GetInvitation() *ClubInvitationRangeSet {
	if m != nil {
		return m.Invitation
	}
	return nil
}

func (m *ClubTypeRangeSet) GetSuggestion() *ClubSuggestionRangeSet {
	if m != nil {
		return m.Suggestion
	}
	return nil
}

func (m *ClubTypeRangeSet) GetTicket() *ClubTicketRangeSet {
	if m != nil {
		return m.Ticket
	}
	return nil
}

func (m *ClubTypeRangeSet) GetBan() *ClubBanRangeSet {
	if m != nil {
		return m.Ban
	}
	return nil
}

type ClubMemberRangeSet struct {
	Count                *protocol.UnsignedIntRange `protobuf:"bytes,1,opt,name=count" json:"count,omitempty"`
	Voice                *protocol.UnsignedIntRange `protobuf:"bytes,3,opt,name=voice" json:"voice,omitempty"`
	StreamSubscriptions  *protocol.UnsignedIntRange `protobuf:"bytes,5,opt,name=stream_subscriptions,json=streamSubscriptions" json:"stream_subscriptions,omitempty"`
	NoteRange            *protocol.UnsignedIntRange `protobuf:"bytes,7,opt,name=note_range,json=noteRange" json:"note_range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ClubMemberRangeSet) Reset()         { *m = ClubMemberRangeSet{} }
func (m *ClubMemberRangeSet) String() string { return proto.CompactTextString(m) }
func (*ClubMemberRangeSet) ProtoMessage()    {}
func (*ClubMemberRangeSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_a06cd3d74328deaa, []int{1}
}

func (m *ClubMemberRangeSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubMemberRangeSet.Unmarshal(m, b)
}
func (m *ClubMemberRangeSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubMemberRangeSet.Marshal(b, m, deterministic)
}
func (m *ClubMemberRangeSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubMemberRangeSet.Merge(m, src)
}
func (m *ClubMemberRangeSet) XXX_Size() int {
	return xxx_messageInfo_ClubMemberRangeSet.Size(m)
}
func (m *ClubMemberRangeSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubMemberRangeSet.DiscardUnknown(m)
}

var xxx_messageInfo_ClubMemberRangeSet proto.InternalMessageInfo

func (m *ClubMemberRangeSet) GetCount() *protocol.UnsignedIntRange {
	if m != nil {
		return m.Count
	}
	return nil
}

func (m *ClubMemberRangeSet) GetVoice() *protocol.UnsignedIntRange {
	if m != nil {
		return m.Voice
	}
	return nil
}

func (m *ClubMemberRangeSet) GetStreamSubscriptions() *protocol.UnsignedIntRange {
	if m != nil {
		return m.StreamSubscriptions
	}
	return nil
}

func (m *ClubMemberRangeSet) GetNoteRange() *protocol.UnsignedIntRange {
	if m != nil {
		return m.NoteRange
	}
	return nil
}

type ClubStreamRangeSet struct {
	Count                *protocol.UnsignedIntRange `protobuf:"bytes,1,opt,name=count" json:"count,omitempty"`
	NameRange            *protocol.UnsignedIntRange `protobuf:"bytes,3,opt,name=name_range,json=nameRange" json:"name_range,omitempty"`
	SubjectRange         *protocol.UnsignedIntRange `protobuf:"bytes,4,opt,name=subject_range,json=subjectRange" json:"subject_range,omitempty"`
	MessageRange         *protocol.UnsignedIntRange `protobuf:"bytes,5,opt,name=message_range,json=messageRange" json:"message_range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ClubStreamRangeSet) Reset()         { *m = ClubStreamRangeSet{} }
func (m *ClubStreamRangeSet) String() string { return proto.CompactTextString(m) }
func (*ClubStreamRangeSet) ProtoMessage()    {}
func (*ClubStreamRangeSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_a06cd3d74328deaa, []int{2}
}

func (m *ClubStreamRangeSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubStreamRangeSet.Unmarshal(m, b)
}
func (m *ClubStreamRangeSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubStreamRangeSet.Marshal(b, m, deterministic)
}
func (m *ClubStreamRangeSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubStreamRangeSet.Merge(m, src)
}
func (m *ClubStreamRangeSet) XXX_Size() int {
	return xxx_messageInfo_ClubStreamRangeSet.Size(m)
}
func (m *ClubStreamRangeSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubStreamRangeSet.DiscardUnknown(m)
}

var xxx_messageInfo_ClubStreamRangeSet proto.InternalMessageInfo

func (m *ClubStreamRangeSet) GetCount() *protocol.UnsignedIntRange {
	if m != nil {
		return m.Count
	}
	return nil
}

func (m *ClubStreamRangeSet) GetNameRange() *protocol.UnsignedIntRange {
	if m != nil {
		return m.NameRange
	}
	return nil
}

func (m *ClubStreamRangeSet) GetSubjectRange() *protocol.UnsignedIntRange {
	if m != nil {
		return m.SubjectRange
	}
	return nil
}

func (m *ClubStreamRangeSet) GetMessageRange() *protocol.UnsignedIntRange {
	if m != nil {
		return m.MessageRange
	}
	return nil
}

type ClubInvitationRangeSet struct {
	Count                *protocol.UnsignedIntRange `protobuf:"bytes,1,opt,name=count" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ClubInvitationRangeSet) Reset()         { *m = ClubInvitationRangeSet{} }
func (m *ClubInvitationRangeSet) String() string { return proto.CompactTextString(m) }
func (*ClubInvitationRangeSet) ProtoMessage()    {}
func (*ClubInvitationRangeSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_a06cd3d74328deaa, []int{3}
}

func (m *ClubInvitationRangeSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubInvitationRangeSet.Unmarshal(m, b)
}
func (m *ClubInvitationRangeSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubInvitationRangeSet.Marshal(b, m, deterministic)
}
func (m *ClubInvitationRangeSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubInvitationRangeSet.Merge(m, src)
}
func (m *ClubInvitationRangeSet) XXX_Size() int {
	return xxx_messageInfo_ClubInvitationRangeSet.Size(m)
}
func (m *ClubInvitationRangeSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubInvitationRangeSet.DiscardUnknown(m)
}

var xxx_messageInfo_ClubInvitationRangeSet proto.InternalMessageInfo

func (m *ClubInvitationRangeSet) GetCount() *protocol.UnsignedIntRange {
	if m != nil {
		return m.Count
	}
	return nil
}

type ClubSuggestionRangeSet struct {
	Count                *protocol.UnsignedIntRange `protobuf:"bytes,1,opt,name=count" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ClubSuggestionRangeSet) Reset()         { *m = ClubSuggestionRangeSet{} }
func (m *ClubSuggestionRangeSet) String() string { return proto.CompactTextString(m) }
func (*ClubSuggestionRangeSet) ProtoMessage()    {}
func (*ClubSuggestionRangeSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_a06cd3d74328deaa, []int{4}
}

func (m *ClubSuggestionRangeSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubSuggestionRangeSet.Unmarshal(m, b)
}
func (m *ClubSuggestionRangeSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubSuggestionRangeSet.Marshal(b, m, deterministic)
}
func (m *ClubSuggestionRangeSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubSuggestionRangeSet.Merge(m, src)
}
func (m *ClubSuggestionRangeSet) XXX_Size() int {
	return xxx_messageInfo_ClubSuggestionRangeSet.Size(m)
}
func (m *ClubSuggestionRangeSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubSuggestionRangeSet.DiscardUnknown(m)
}

var xxx_messageInfo_ClubSuggestionRangeSet proto.InternalMessageInfo

func (m *ClubSuggestionRangeSet) GetCount() *protocol.UnsignedIntRange {
	if m != nil {
		return m.Count
	}
	return nil
}

type ClubTicketRangeSet struct {
	Count                *protocol.UnsignedIntRange `protobuf:"bytes,1,opt,name=count" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ClubTicketRangeSet) Reset()         { *m = ClubTicketRangeSet{} }
func (m *ClubTicketRangeSet) String() string { return proto.CompactTextString(m) }
func (*ClubTicketRangeSet) ProtoMessage()    {}
func (*ClubTicketRangeSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_a06cd3d74328deaa, []int{5}
}

func (m *ClubTicketRangeSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubTicketRangeSet.Unmarshal(m, b)
}
func (m *ClubTicketRangeSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubTicketRangeSet.Marshal(b, m, deterministic)
}
func (m *ClubTicketRangeSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubTicketRangeSet.Merge(m, src)
}
func (m *ClubTicketRangeSet) XXX_Size() int {
	return xxx_messageInfo_ClubTicketRangeSet.Size(m)
}
func (m *ClubTicketRangeSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubTicketRangeSet.DiscardUnknown(m)
}

var xxx_messageInfo_ClubTicketRangeSet proto.InternalMessageInfo

func (m *ClubTicketRangeSet) GetCount() *protocol.UnsignedIntRange {
	if m != nil {
		return m.Count
	}
	return nil
}

type ClubBanRangeSet struct {
	Count                *protocol.UnsignedIntRange `protobuf:"bytes,1,opt,name=count" json:"count,omitempty"`
	ReasonRange          *protocol.UnsignedIntRange `protobuf:"bytes,3,opt,name=reason_range,json=reasonRange" json:"reason_range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ClubBanRangeSet) Reset()         { *m = ClubBanRangeSet{} }
func (m *ClubBanRangeSet) String() string { return proto.CompactTextString(m) }
func (*ClubBanRangeSet) ProtoMessage()    {}
func (*ClubBanRangeSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_a06cd3d74328deaa, []int{6}
}

func (m *ClubBanRangeSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubBanRangeSet.Unmarshal(m, b)
}
func (m *ClubBanRangeSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubBanRangeSet.Marshal(b, m, deterministic)
}
func (m *ClubBanRangeSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubBanRangeSet.Merge(m, src)
}
func (m *ClubBanRangeSet) XXX_Size() int {
	return xxx_messageInfo_ClubBanRangeSet.Size(m)
}
func (m *ClubBanRangeSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubBanRangeSet.DiscardUnknown(m)
}

var xxx_messageInfo_ClubBanRangeSet proto.InternalMessageInfo

func (m *ClubBanRangeSet) GetCount() *protocol.UnsignedIntRange {
	if m != nil {
		return m.Count
	}
	return nil
}

func (m *ClubBanRangeSet) GetReasonRange() *protocol.UnsignedIntRange {
	if m != nil {
		return m.ReasonRange
	}
	return nil
}

func init() {
	proto.RegisterType((*ClubTypeRangeSet)(nil), "bgs.protocol.club.v1.ClubTypeRangeSet")
	proto.RegisterType((*ClubMemberRangeSet)(nil), "bgs.protocol.club.v1.ClubMemberRangeSet")
	proto.RegisterType((*ClubStreamRangeSet)(nil), "bgs.protocol.club.v1.ClubStreamRangeSet")
	proto.RegisterType((*ClubInvitationRangeSet)(nil), "bgs.protocol.club.v1.ClubInvitationRangeSet")
	proto.RegisterType((*ClubSuggestionRangeSet)(nil), "bgs.protocol.club.v1.ClubSuggestionRangeSet")
	proto.RegisterType((*ClubTicketRangeSet)(nil), "bgs.protocol.club.v1.ClubTicketRangeSet")
	proto.RegisterType((*ClubBanRangeSet)(nil), "bgs.protocol.club.v1.ClubBanRangeSet")
}

func init() { proto.RegisterFile("club_range_set.proto", fileDescriptor_a06cd3d74328deaa) }

var fileDescriptor_a06cd3d74328deaa = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0x87, 0xb5, 0x95, 0x82, 0xe6, 0x15, 0x56, 0x42, 0x85, 0xc2, 0x60, 0x13, 0xaa, 0x84, 0xb4,
	0x0b, 0x94, 0x6c, 0x08, 0x09, 0x09, 0x81, 0x04, 0xdb, 0x05, 0x8c, 0x3f, 0x93, 0x68, 0xc7, 0x0d,
	0x37, 0x95, 0xed, 0x1e, 0xdc, 0x40, 0x63, 0x47, 0x3e, 0x4e, 0x05, 0xaf, 0xc0, 0x25, 0xbc, 0x16,
	0x0f, 0x85, 0x6c, 0xa7, 0x49, 0xcb, 0x36, 0x35, 0xcd, 0x9d, 0x5b, 0x9d, 0xef, 0x8b, 0xcf, 0xcf,
	0x3e, 0x26, 0x3d, 0x3e, 0xcd, 0xd9, 0x48, 0x53, 0x29, 0x60, 0x84, 0x60, 0xa2, 0x4c, 0x2b, 0xa3,
	0x82, 0x1e, 0x13, 0xe8, 0x97, 0x5c, 0x4d, 0x23, 0x5b, 0x12, 0xcd, 0x8e, 0x76, 0xf7, 0xc4, 0x54,
	0x31, 0x3a, 0x1d, 0xc1, 0x0f, 0x03, 0x12, 0x13, 0x25, 0x31, 0x76, 0xa0, 0xaf, 0xec, 0xff, 0x6d,
	0x93, 0xee, 0xc9, 0x34, 0x67, 0xe7, 0x3f, 0x33, 0x18, 0xd8, 0xff, 0x87, 0x60, 0x82, 0x97, 0x84,
	0x48, 0x9a, 0x82, 0xff, 0x42, 0xb8, 0xf9, 0x70, 0xe3, 0x60, 0xfb, 0xc9, 0x7e, 0xb4, 0xa4, 0xff,
	0x2c, 0x31, 0x11, 0x12, 0xc6, 0xa7, 0xd2, 0x38, 0x6c, 0xb0, 0x65, 0x09, 0xb7, 0x0c, 0xde, 0x93,
	0xdb, 0x63, 0x40, 0xae, 0x93, 0xcc, 0x24, 0x4a, 0x16, 0x96, 0x56, 0x2d, 0x4b, 0x77, 0x01, 0xf4,
	0xb2, 0x37, 0x64, 0x87, 0x69, 0x45, 0xc7, 0x9c, 0xa2, 0x29, 0x54, 0xd7, 0x6a, 0xa9, 0x6e, 0x95,
	0x98, 0x17, 0xbd, 0x25, 0x5d, 0x9c, 0x28, 0x6d, 0x46, 0x0b, 0xad, 0xdd, 0xa8, 0x67, 0x72, 0xdc,
	0x59, 0xd9, 0xdf, 0x2b, 0x72, 0x3d, 0x85, 0x94, 0x81, 0x0e, 0xef, 0x39, 0xfe, 0x20, 0xba, 0x2c,
	0xf9, 0xc8, 0xc6, 0xfa, 0xd1, 0xd5, 0xcd, 0x83, 0x1d, 0x14, 0x9c, 0x35, 0xa0, 0xd1, 0x40, 0xd3,
	0x70, 0x77, 0x95, 0x61, 0xe8, 0xea, 0x2a, 0x83, 0xe7, 0x82, 0x0f, 0x84, 0x24, 0x72, 0x96, 0x18,
	0x6a, 0x93, 0x0a, 0xef, 0x3b, 0xcb, 0xe3, 0xab, 0x2d, 0xa7, 0x65, 0x6d, 0x69, 0x5a, 0xe0, 0xad,
	0x0d, 0x73, 0x21, 0x00, 0x9d, 0xed, 0xc1, 0x2a, 0xdb, 0xb0, 0xac, 0xad, 0x6c, 0x15, 0x6f, 0xbb,
	0x33, 0x09, 0xff, 0x0e, 0x26, 0xdc, 0x5b, 0xd5, 0xdd, 0xb9, 0xab, 0xab, 0xba, 0xf3, 0x5c, 0xf0,
	0x8c, 0xb4, 0x18, 0x95, 0xe1, 0xbe, 0xc3, 0x1f, 0x5d, 0x8d, 0x1f, 0xd3, 0x6a, 0x07, 0x96, 0xe8,
	0xff, 0xde, 0x24, 0xc1, 0xc5, 0xdc, 0x83, 0xa7, 0xa4, 0xcd, 0x55, 0x2e, 0x4d, 0xb8, 0x51, 0xeb,
	0xc0, 0x7d, 0xb1, 0xa5, 0x66, 0x2a, 0xe1, 0x75, 0xef, 0xae, 0x2f, 0x0e, 0x3e, 0x91, 0x9e, 0x3f,
	0xa3, 0x11, 0xe6, 0xac, 0xbc, 0xcc, 0x18, 0xb6, 0x6b, 0x49, 0xee, 0x78, 0x76, 0xb8, 0x88, 0xba,
	0x79, 0x54, 0x66, 0xbd, 0x4b, 0xbb, 0x65, 0x09, 0xb7, 0xec, 0xff, 0x29, 0x42, 0x59, 0xbe, 0x4a,
	0x0d, 0x43, 0x59, 0x7e, 0x1b, 0x5a, 0xeb, 0xbe, 0x0d, 0x27, 0xe4, 0x26, 0xe6, 0xec, 0x1b, 0xf0,
	0xf5, 0x86, 0xb9, 0x53, 0x40, 0xa5, 0x24, 0x05, 0x44, 0x2a, 0xe6, 0xdb, 0xa8, 0x97, 0x6d, 0xa7,
	0x80, 0x7c, 0x2a, 0x67, 0xe4, 0xee, 0xe5, 0x93, 0xd1, 0x2c, 0x98, 0xb9, 0xef, 0xe2, 0x6c, 0x34,
	0xf4, 0xbd, 0xf3, 0x87, 0xb6, 0x3c, 0x21, 0x0d, 0x5d, 0xbf, 0x36, 0xc8, 0xce, 0x7f, 0xf3, 0xd2,
	0xf0, 0xf8, 0x5f, 0x93, 0x8e, 0x06, 0x8a, 0x6b, 0x3e, 0xeb, 0xdb, 0x9e, 0x71, 0x3f, 0x8e, 0x5f,
	0x7c, 0x79, 0x2e, 0x12, 0x33, 0xc9, 0x59, 0xc4, 0x55, 0x1a, 0x63, 0x9e, 0x81, 0xce, 0x0e, 0x0f,
	0x4d, 0x2c, 0x54, 0x36, 0x01, 0xcd, 0x35, 0xfd, 0x6a, 0x62, 0x26, 0xc1, 0xc4, 0x4c, 0x60, 0x3c,
	0x77, 0xc6, 0x76, 0xec, 0xe3, 0xd9, 0xd1, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x49, 0xae,
	0x7a, 0xfc, 0x06, 0x00, 0x00,
}
