// Code generated by protoc-gen-gcraft. DO NOT EDIT.
// source: club_ban.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v2 "github.com/superp00t/gophercraft/bnet/bgs/protocol/v2"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddBanOptions struct {
	TargetId             *MemberId       `protobuf:"bytes,1,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
	Attribute            []*v2.Attribute `protobuf:"bytes,2,rep,name=attribute" json:"attribute,omitempty"`
	Reason               *string         `protobuf:"bytes,3,opt,name=reason" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddBanOptions) Reset()         { *m = AddBanOptions{} }
func (m *AddBanOptions) String() string { return proto.CompactTextString(m) }
func (*AddBanOptions) ProtoMessage()    {}
func (*AddBanOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee1cc033b0fb491a, []int{0}
}

func (m *AddBanOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBanOptions.Unmarshal(m, b)
}
func (m *AddBanOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBanOptions.Marshal(b, m, deterministic)
}
func (m *AddBanOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBanOptions.Merge(m, src)
}
func (m *AddBanOptions) XXX_Size() int {
	return xxx_messageInfo_AddBanOptions.Size(m)
}
func (m *AddBanOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBanOptions.DiscardUnknown(m)
}

var xxx_messageInfo_AddBanOptions proto.InternalMessageInfo

func (m *AddBanOptions) GetTargetId() *MemberId {
	if m != nil {
		return m.TargetId
	}
	return nil
}

func (m *AddBanOptions) GetAttribute() []*v2.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *AddBanOptions) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

type ClubBan struct {
	Id                   *MemberId          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	BattleTag            *string            `protobuf:"bytes,2,opt,name=battle_tag,json=battleTag" json:"battle_tag,omitempty"`
	Creator              *MemberDescription `protobuf:"bytes,3,opt,name=creator" json:"creator,omitempty"`
	Attribute            []*v2.Attribute    `protobuf:"bytes,4,rep,name=attribute" json:"attribute,omitempty"`
	Reason               *string            `protobuf:"bytes,5,opt,name=reason" json:"reason,omitempty"`
	CreationTime         *uint64            `protobuf:"varint,6,opt,name=creation_time,json=creationTime" json:"creation_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ClubBan) Reset()         { *m = ClubBan{} }
func (m *ClubBan) String() string { return proto.CompactTextString(m) }
func (*ClubBan) ProtoMessage()    {}
func (*ClubBan) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee1cc033b0fb491a, []int{1}
}

func (m *ClubBan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubBan.Unmarshal(m, b)
}
func (m *ClubBan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubBan.Marshal(b, m, deterministic)
}
func (m *ClubBan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubBan.Merge(m, src)
}
func (m *ClubBan) XXX_Size() int {
	return xxx_messageInfo_ClubBan.Size(m)
}
func (m *ClubBan) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubBan.DiscardUnknown(m)
}

var xxx_messageInfo_ClubBan proto.InternalMessageInfo

func (m *ClubBan) GetId() *MemberId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ClubBan) GetBattleTag() string {
	if m != nil && m.BattleTag != nil {
		return *m.BattleTag
	}
	return ""
}

func (m *ClubBan) GetCreator() *MemberDescription {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *ClubBan) GetAttribute() []*v2.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *ClubBan) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

func (m *ClubBan) GetCreationTime() uint64 {
	if m != nil && m.CreationTime != nil {
		return *m.CreationTime
	}
	return 0
}

func init() {
	proto.RegisterType((*AddBanOptions)(nil), "bgs.protocol.club.v1.AddBanOptions")
	proto.RegisterType((*ClubBan)(nil), "bgs.protocol.club.v1.ClubBan")
}

func init() { proto.RegisterFile("club_ban.proto", fileDescriptor_ee1cc033b0fb491a) }

var fileDescriptor_ee1cc033b0fb491a = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x50, 0x4f, 0x4b, 0xf3, 0x30,
	0x18, 0xa7, 0xdd, 0xde, 0xed, 0x6d, 0xe6, 0x04, 0x83, 0x48, 0x19, 0x28, 0x65, 0x3b, 0xd8, 0x53,
	0xb2, 0xf5, 0x24, 0xea, 0x65, 0xd3, 0xcb, 0x0e, 0x22, 0x94, 0x9d, 0xbc, 0x94, 0xa4, 0x8d, 0x5d,
	0xa0, 0x4d, 0x4a, 0xfa, 0xb4, 0xe0, 0xd7, 0xf0, 0x03, 0xf8, 0x59, 0x65, 0xed, 0xaa, 0x0e, 0x44,
	0xc4, 0x5b, 0xf2, 0x3c, 0xbf, 0xbf, 0x0f, 0x3a, 0x8e, 0xb3, 0x8a, 0x47, 0x9c, 0x29, 0x52, 0x18,
	0x0d, 0x1a, 0x9f, 0xf2, 0xb4, 0x6c, 0x9f, 0xb1, 0xce, 0xc8, 0x6e, 0x49, 0xea, 0xc5, 0xe4, 0xa4,
	0x41, 0xe5, 0x22, 0xe7, 0xc2, 0xb4, 0xdb, 0xc9, 0x8c, 0x15, 0x92, 0xc6, 0x99, 0x14, 0x0a, 0x68,
	0x1d, 0x50, 0x06, 0x60, 0x24, 0xaf, 0x40, 0x44, 0xf0, 0x52, 0x88, 0xbd, 0xc4, 0xf4, 0xcd, 0x42,
	0xe3, 0x65, 0x92, 0xac, 0x98, 0x7a, 0x2c, 0x40, 0x6a, 0x55, 0xe2, 0x1b, 0xe4, 0x00, 0x33, 0xa9,
	0x80, 0x48, 0x26, 0xae, 0xe5, 0x59, 0xfe, 0x28, 0xb8, 0x20, 0xdf, 0x79, 0x92, 0x87, 0xc6, 0x6d,
	0x9d, 0x84, 0xff, 0x5b, 0xc2, 0x3a, 0xc1, 0x57, 0xc8, 0xf9, 0xf0, 0x71, 0x6d, 0xaf, 0xe7, 0x8f,
	0x82, 0xc9, 0x21, 0xb9, 0x0e, 0xc8, 0xb2, 0x43, 0x84, 0x9f, 0x60, 0x7c, 0x86, 0x06, 0x46, 0xb0,
	0x52, 0x2b, 0xb7, 0xe7, 0x59, 0xbe, 0x13, 0xee, 0x7f, 0xd3, 0x57, 0x1b, 0x0d, 0xef, 0xb2, 0x8a,
	0xaf, 0x98, 0xc2, 0x04, 0xd9, 0xbf, 0xce, 0x64, 0xcb, 0x04, 0x9f, 0x23, 0xc4, 0x19, 0x40, 0x26,
	0x22, 0x60, 0xa9, 0x6b, 0x37, 0xba, 0x4e, 0x3b, 0xd9, 0xb0, 0x14, 0x2f, 0xd1, 0x30, 0x36, 0x82,
	0x81, 0x36, 0x8d, 0xe7, 0x28, 0xb8, 0xfc, 0x49, 0xf3, 0x5e, 0x94, 0xb1, 0x91, 0xcd, 0x91, 0xc2,
	0x8e, 0x77, 0xd8, 0xb7, 0xff, 0xb7, 0xbe, 0xff, 0xbe, 0xf6, 0xc5, 0x33, 0x34, 0x6e, 0xc4, 0xa5,
	0x56, 0x11, 0xc8, 0x5c, 0xb8, 0x03, 0xcf, 0xf2, 0xfb, 0xe1, 0x51, 0x37, 0xdc, 0xc8, 0x5c, 0xac,
	0x6e, 0x9f, 0xae, 0x53, 0x09, 0xdb, 0x8a, 0x93, 0x58, 0xe7, 0xb4, 0xac, 0x0a, 0x61, 0x8a, 0xf9,
	0x1c, 0x68, 0xaa, 0x8b, 0xad, 0x30, 0xb1, 0x61, 0xcf, 0x40, 0xb9, 0x12, 0x40, 0x79, 0x5a, 0xd2,
	0x2e, 0x0a, 0xdd, 0xf5, 0xa1, 0xf5, 0xe2, 0x3d, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xa7, 0x3a, 0x96,
	0x52, 0x02, 0x00, 0x00,
}
