// Code generated by protoc-gen-gcraft. DO NOT EDIT.
// source: presence_service.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	protocol "github.com/superp00t/gophercraft/bnet/bgs/protocol"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubscribeRequest struct {
	AgentId              *protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	EntityId             *protocol.EntityId `protobuf:"bytes,2,req,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	ObjectId             *uint64            `protobuf:"varint,3,req,name=object_id,json=objectId" json:"object_id,omitempty"`
	Program              []uint32           `protobuf:"fixed32,4,rep,name=program" json:"program,omitempty"`
	Key                  []*FieldKey        `protobuf:"bytes,6,rep,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f374631eb4c1391c, []int{0}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetAgentId() *protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *SubscribeRequest) GetEntityId() *protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *SubscribeRequest) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

func (m *SubscribeRequest) GetProgram() []uint32 {
	if m != nil {
		return m.Program
	}
	return nil
}

func (m *SubscribeRequest) GetKey() []*FieldKey {
	if m != nil {
		return m.Key
	}
	return nil
}

type SubscribeNotificationRequest struct {
	EntityId             *protocol.EntityId `protobuf:"bytes,1,req,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SubscribeNotificationRequest) Reset()         { *m = SubscribeNotificationRequest{} }
func (m *SubscribeNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeNotificationRequest) ProtoMessage()    {}
func (*SubscribeNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f374631eb4c1391c, []int{1}
}

func (m *SubscribeNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeNotificationRequest.Unmarshal(m, b)
}
func (m *SubscribeNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeNotificationRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeNotificationRequest.Merge(m, src)
}
func (m *SubscribeNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeNotificationRequest.Size(m)
}
func (m *SubscribeNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeNotificationRequest proto.InternalMessageInfo

func (m *SubscribeNotificationRequest) GetEntityId() *protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

type UnsubscribeRequest struct {
	AgentId              *protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	EntityId             *protocol.EntityId `protobuf:"bytes,2,req,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	ObjectId             *uint64            `protobuf:"varint,3,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UnsubscribeRequest) Reset()         { *m = UnsubscribeRequest{} }
func (m *UnsubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeRequest) ProtoMessage()    {}
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f374631eb4c1391c, []int{2}
}

func (m *UnsubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeRequest.Unmarshal(m, b)
}
func (m *UnsubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeRequest.Marshal(b, m, deterministic)
}
func (m *UnsubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeRequest.Merge(m, src)
}
func (m *UnsubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeRequest.Size(m)
}
func (m *UnsubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeRequest proto.InternalMessageInfo

func (m *UnsubscribeRequest) GetAgentId() *protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *UnsubscribeRequest) GetEntityId() *protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *UnsubscribeRequest) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

type UpdateRequest struct {
	EntityId             *protocol.EntityId `protobuf:"bytes,1,req,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	FieldOperation       []*FieldOperation  `protobuf:"bytes,2,rep,name=field_operation,json=fieldOperation" json:"field_operation,omitempty"`
	NoCreate             *bool              `protobuf:"varint,3,opt,name=no_create,json=noCreate" json:"no_create,omitempty"`
	AgentId              *protocol.EntityId `protobuf:"bytes,4,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f374631eb4c1391c, []int{3}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetEntityId() *protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *UpdateRequest) GetFieldOperation() []*FieldOperation {
	if m != nil {
		return m.FieldOperation
	}
	return nil
}

func (m *UpdateRequest) GetNoCreate() bool {
	if m != nil && m.NoCreate != nil {
		return *m.NoCreate
	}
	return false
}

func (m *UpdateRequest) GetAgentId() *protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

type QueryRequest struct {
	EntityId             *protocol.EntityId `protobuf:"bytes,1,req,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	Key                  []*FieldKey        `protobuf:"bytes,2,rep,name=key" json:"key,omitempty"`
	AgentId              *protocol.EntityId `protobuf:"bytes,3,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f374631eb4c1391c, []int{4}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetEntityId() *protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *QueryRequest) GetKey() []*FieldKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *QueryRequest) GetAgentId() *protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

type QueryResponse struct {
	Field                []*Field `protobuf:"bytes,2,rep,name=field" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f374631eb4c1391c, []int{5}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetField() []*Field {
	if m != nil {
		return m.Field
	}
	return nil
}

type OwnershipRequest struct {
	EntityId             *protocol.EntityId `protobuf:"bytes,1,req,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	ReleaseOwnership     *bool              `protobuf:"varint,2,opt,name=release_ownership,json=releaseOwnership" json:"release_ownership,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OwnershipRequest) Reset()         { *m = OwnershipRequest{} }
func (m *OwnershipRequest) String() string { return proto.CompactTextString(m) }
func (*OwnershipRequest) ProtoMessage()    {}
func (*OwnershipRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f374631eb4c1391c, []int{6}
}

func (m *OwnershipRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnershipRequest.Unmarshal(m, b)
}
func (m *OwnershipRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnershipRequest.Marshal(b, m, deterministic)
}
func (m *OwnershipRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnershipRequest.Merge(m, src)
}
func (m *OwnershipRequest) XXX_Size() int {
	return xxx_messageInfo_OwnershipRequest.Size(m)
}
func (m *OwnershipRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnershipRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OwnershipRequest proto.InternalMessageInfo

func (m *OwnershipRequest) GetEntityId() *protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *OwnershipRequest) GetReleaseOwnership() bool {
	if m != nil && m.ReleaseOwnership != nil {
		return *m.ReleaseOwnership
	}
	return false
}

type BatchSubscribeRequest struct {
	AgentId              *protocol.EntityId   `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	EntityId             []*protocol.EntityId `protobuf:"bytes,2,rep,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	Program              []uint32             `protobuf:"fixed32,3,rep,name=program" json:"program,omitempty"`
	Key                  []*FieldKey          `protobuf:"bytes,4,rep,name=key" json:"key,omitempty"`
	ObjectId             *uint64              `protobuf:"varint,5,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BatchSubscribeRequest) Reset()         { *m = BatchSubscribeRequest{} }
func (m *BatchSubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*BatchSubscribeRequest) ProtoMessage()    {}
func (*BatchSubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f374631eb4c1391c, []int{7}
}

func (m *BatchSubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchSubscribeRequest.Unmarshal(m, b)
}
func (m *BatchSubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchSubscribeRequest.Marshal(b, m, deterministic)
}
func (m *BatchSubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchSubscribeRequest.Merge(m, src)
}
func (m *BatchSubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_BatchSubscribeRequest.Size(m)
}
func (m *BatchSubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchSubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchSubscribeRequest proto.InternalMessageInfo

func (m *BatchSubscribeRequest) GetAgentId() *protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *BatchSubscribeRequest) GetEntityId() []*protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *BatchSubscribeRequest) GetProgram() []uint32 {
	if m != nil {
		return m.Program
	}
	return nil
}

func (m *BatchSubscribeRequest) GetKey() []*FieldKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *BatchSubscribeRequest) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

type SubscribeResult struct {
	EntityId             *protocol.EntityId `protobuf:"bytes,1,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	Result               *uint32            `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SubscribeResult) Reset()         { *m = SubscribeResult{} }
func (m *SubscribeResult) String() string { return proto.CompactTextString(m) }
func (*SubscribeResult) ProtoMessage()    {}
func (*SubscribeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_f374631eb4c1391c, []int{8}
}

func (m *SubscribeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeResult.Unmarshal(m, b)
}
func (m *SubscribeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeResult.Marshal(b, m, deterministic)
}
func (m *SubscribeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeResult.Merge(m, src)
}
func (m *SubscribeResult) XXX_Size() int {
	return xxx_messageInfo_SubscribeResult.Size(m)
}
func (m *SubscribeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeResult.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeResult proto.InternalMessageInfo

func (m *SubscribeResult) GetEntityId() *protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *SubscribeResult) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type BatchSubscribeResponse struct {
	SubscribeFailed      []*SubscribeResult `protobuf:"bytes,1,rep,name=subscribe_failed,json=subscribeFailed" json:"subscribe_failed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BatchSubscribeResponse) Reset()         { *m = BatchSubscribeResponse{} }
func (m *BatchSubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*BatchSubscribeResponse) ProtoMessage()    {}
func (*BatchSubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f374631eb4c1391c, []int{9}
}

func (m *BatchSubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchSubscribeResponse.Unmarshal(m, b)
}
func (m *BatchSubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchSubscribeResponse.Marshal(b, m, deterministic)
}
func (m *BatchSubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchSubscribeResponse.Merge(m, src)
}
func (m *BatchSubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_BatchSubscribeResponse.Size(m)
}
func (m *BatchSubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchSubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchSubscribeResponse proto.InternalMessageInfo

func (m *BatchSubscribeResponse) GetSubscribeFailed() []*SubscribeResult {
	if m != nil {
		return m.SubscribeFailed
	}
	return nil
}

type BatchUnsubscribeRequest struct {
	AgentId              *protocol.EntityId   `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	EntityId             []*protocol.EntityId `protobuf:"bytes,2,rep,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	ObjectId             *uint64              `protobuf:"varint,3,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BatchUnsubscribeRequest) Reset()         { *m = BatchUnsubscribeRequest{} }
func (m *BatchUnsubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*BatchUnsubscribeRequest) ProtoMessage()    {}
func (*BatchUnsubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f374631eb4c1391c, []int{10}
}

func (m *BatchUnsubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchUnsubscribeRequest.Unmarshal(m, b)
}
func (m *BatchUnsubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchUnsubscribeRequest.Marshal(b, m, deterministic)
}
func (m *BatchUnsubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchUnsubscribeRequest.Merge(m, src)
}
func (m *BatchUnsubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_BatchUnsubscribeRequest.Size(m)
}
func (m *BatchUnsubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchUnsubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchUnsubscribeRequest proto.InternalMessageInfo

func (m *BatchUnsubscribeRequest) GetAgentId() *protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *BatchUnsubscribeRequest) GetEntityId() []*protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *BatchUnsubscribeRequest) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

func init() {
	proto.RegisterType((*SubscribeRequest)(nil), "bgs.protocol.presence.v1.SubscribeRequest")
	proto.RegisterType((*SubscribeNotificationRequest)(nil), "bgs.protocol.presence.v1.SubscribeNotificationRequest")
	proto.RegisterType((*UnsubscribeRequest)(nil), "bgs.protocol.presence.v1.UnsubscribeRequest")
	proto.RegisterType((*UpdateRequest)(nil), "bgs.protocol.presence.v1.UpdateRequest")
	proto.RegisterType((*QueryRequest)(nil), "bgs.protocol.presence.v1.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "bgs.protocol.presence.v1.QueryResponse")
	proto.RegisterType((*OwnershipRequest)(nil), "bgs.protocol.presence.v1.OwnershipRequest")
	proto.RegisterType((*BatchSubscribeRequest)(nil), "bgs.protocol.presence.v1.BatchSubscribeRequest")
	proto.RegisterType((*SubscribeResult)(nil), "bgs.protocol.presence.v1.SubscribeResult")
	proto.RegisterType((*BatchSubscribeResponse)(nil), "bgs.protocol.presence.v1.BatchSubscribeResponse")
	proto.RegisterType((*BatchUnsubscribeRequest)(nil), "bgs.protocol.presence.v1.BatchUnsubscribeRequest")
}

func init() { proto.RegisterFile("presence_service.proto", fileDescriptor_f374631eb4c1391c) }

var fileDescriptor_f374631eb4c1391c = []byte{
	// 758 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0x6c, 0xe7, 0xc7, 0xb9, 0xfd, 0xda, 0x84, 0x51, 0x1b, 0xac, 0x80, 0x44, 0xe4, 0x45,
	0x1b, 0x1a, 0x14, 0x37, 0xe5, 0x67, 0x89, 0x50, 0x0b, 0x95, 0x2a, 0xa4, 0x96, 0xba, 0x74, 0x01,
	0x0b, 0x82, 0xe3, 0xdc, 0x24, 0x86, 0xd4, 0x36, 0xe3, 0x49, 0x51, 0xc4, 0x06, 0x75, 0xc9, 0x1b,
	0xb0, 0xe1, 0x09, 0x78, 0x28, 0x76, 0x6c, 0x78, 0x81, 0xec, 0x90, 0x27, 0x76, 0x64, 0xa7, 0xf9,
	0x71, 0x15, 0x55, 0x62, 0x97, 0x71, 0xee, 0x9c, 0x73, 0xcf, 0x99, 0xb9, 0x67, 0xa0, 0xe8, 0x52,
	0xf4, 0xd0, 0x36, 0xb1, 0xe1, 0x21, 0xbd, 0xb0, 0x4c, 0xac, 0xb9, 0xd4, 0x61, 0x0e, 0x51, 0x9a,
	0x1d, 0x6f, 0xf4, 0xd3, 0x74, 0x7a, 0xb5, 0xb0, 0xa8, 0x76, 0x51, 0x2f, 0x11, 0xb4, 0x99, 0xc5,
	0x06, 0x0d, 0x36, 0x70, 0x31, 0x28, 0x29, 0xad, 0x8f, 0x51, 0xa2, 0x5f, 0xf3, 0xd4, 0x35, 0xa3,
	0x1f, 0xd4, 0xdf, 0x02, 0x14, 0x4e, 0xfb, 0x4d, 0xcf, 0xa4, 0x56, 0x13, 0x75, 0xfc, 0xd4, 0x47,
	0x8f, 0x91, 0x3a, 0xc8, 0x46, 0x07, 0x6d, 0xd6, 0xb0, 0x5a, 0x8a, 0x50, 0x16, 0x2a, 0x2b, 0xbb,
	0xc5, 0x5a, 0x8c, 0xfc, 0x05, 0xe7, 0x3b, 0x6c, 0xe9, 0x59, 0x5e, 0x77, 0xd8, 0x22, 0x0f, 0x21,
	0x17, 0x34, 0x61, 0xb5, 0x14, 0xb1, 0x2c, 0xce, 0xd9, 0x23, 0x63, 0xf0, 0x8b, 0xdc, 0x81, 0x9c,
	0xd3, 0xfc, 0x80, 0x26, 0x27, 0x92, 0xca, 0x62, 0x25, 0xa5, 0xcb, 0xa3, 0x0f, 0x87, 0x2d, 0xa2,
	0x40, 0xd6, 0xa5, 0x4e, 0x87, 0x1a, 0xe7, 0x4a, 0xaa, 0x2c, 0x55, 0xb2, 0x7a, 0xb8, 0x24, 0x8f,
	0x40, 0xfa, 0x88, 0x03, 0x25, 0x53, 0x96, 0x2a, 0x2b, 0xbb, 0x6a, 0x6d, 0x96, 0x2d, 0xb5, 0x03,
	0x0b, 0x7b, 0xad, 0x97, 0x38, 0xd0, 0xfd, 0x72, 0xf5, 0x14, 0xee, 0x8e, 0x85, 0x1e, 0x39, 0xcc,
	0x6a, 0x5b, 0xa6, 0xc1, 0x2c, 0xc7, 0x0e, 0x45, 0xc7, 0x14, 0x08, 0xc9, 0x14, 0xa8, 0xdf, 0x05,
	0x20, 0x67, 0xb6, 0xf7, 0x8f, 0x18, 0x28, 0x44, 0x0d, 0xf4, 0x8f, 0x76, 0xf5, 0xcc, 0x6d, 0x19,
	0x0c, 0x97, 0x91, 0x48, 0x4e, 0x20, 0xdf, 0xf6, 0x8d, 0x6c, 0x38, 0x2e, 0x52, 0xee, 0x98, 0x22,
	0x72, 0xe7, 0x2b, 0x0b, 0x9c, 0x3f, 0x0e, 0xeb, 0xf5, 0xb5, 0x76, 0x6c, 0xed, 0xb7, 0x6d, 0x3b,
	0x0d, 0x93, 0xa2, 0xc1, 0x90, 0xb7, 0x2d, 0xeb, 0xb2, 0xed, 0xec, 0xf3, 0x75, 0xcc, 0xbb, 0x54,
	0x22, 0xef, 0xd4, 0x9f, 0x02, 0xfc, 0x7f, 0xd2, 0x47, 0x3a, 0x58, 0x4a, 0x68, 0x70, 0xad, 0xc4,
	0x6b, 0x5d, 0xab, 0x58, 0xbb, 0x52, 0xb2, 0x76, 0x0f, 0x60, 0x35, 0xe8, 0xd6, 0x73, 0x1d, 0xdb,
	0x43, 0xf2, 0x18, 0xd2, 0xdc, 0xa1, 0x80, 0xfb, 0xde, 0x02, 0x6e, 0x7d, 0x54, 0xad, 0x32, 0x28,
	0x1c, 0x7f, 0xb6, 0x91, 0x7a, 0x5d, 0xcb, 0x5d, 0x4a, 0x79, 0x15, 0x6e, 0x51, 0xec, 0xa1, 0xe1,
	0x61, 0xc3, 0x09, 0x01, 0x15, 0x91, 0x9f, 0x4b, 0x21, 0xf8, 0x63, 0x4c, 0xa4, 0xfe, 0x11, 0x60,
	0x63, 0xcf, 0x60, 0x66, 0xf7, 0x06, 0x62, 0x43, 0x4a, 0xd4, 0x6e, 0x24, 0x19, 0xa4, 0xa9, 0xc9,
	0x90, 0xba, 0xde, 0x11, 0xc6, 0xa6, 0x28, 0x3d, 0x31, 0x45, 0xef, 0x20, 0x1f, 0x11, 0xea, 0xf5,
	0x7b, 0x57, 0x3c, 0x16, 0x12, 0x35, 0x5d, 0x84, 0x0c, 0xe5, 0xdb, 0xb9, 0xb1, 0xab, 0x7a, 0xb0,
	0x52, 0x6d, 0x28, 0x4e, 0xba, 0x19, 0xdc, 0x8a, 0xd7, 0x50, 0x18, 0x07, 0x4b, 0xa3, 0x6d, 0x58,
	0x3d, 0xf4, 0xd9, 0x7c, 0x65, 0xf7, 0x67, 0x2b, 0x9b, 0xe8, 0x55, 0xcf, 0x8f, 0x21, 0x0e, 0x38,
	0x82, 0xfa, 0x43, 0x80, 0xdb, 0x9c, 0xf0, 0x46, 0x62, 0x4b, 0x5a, 0x3a, 0xb6, 0x76, 0x7f, 0x65,
	0x20, 0xff, 0x2a, 0x50, 0x74, 0x3a, 0x7a, 0x00, 0xc9, 0x19, 0xe4, 0xc6, 0xc2, 0xc8, 0x76, 0x22,
	0xf5, 0x5c, 0x51, 0x69, 0x3d, 0x5e, 0x7b, 0xe4, 0x3c, 0x37, 0x98, 0xa1, 0x66, 0x2e, 0x87, 0x55,
	0x51, 0x16, 0xc8, 0x1b, 0x58, 0x89, 0xb8, 0x40, 0x1e, 0xcc, 0x06, 0xbe, 0x6a, 0xd6, 0x5c, 0x68,
	0x91, 0x1c, 0x43, 0x66, 0x94, 0xbd, 0x64, 0x6b, 0x0e, 0x6a, 0x34, 0x9d, 0xe7, 0x02, 0x4a, 0xe4,
	0x3d, 0xa4, 0x79, 0x68, 0x90, 0xcd, 0xd9, 0x78, 0xd1, 0x0c, 0x2c, 0x6d, 0x2d, 0xac, 0x1b, 0xdd,
	0xb3, 0x80, 0x21, 0xe5, 0x9b, 0x3c, 0x9e, 0xf2, 0x79, 0x26, 0x4f, 0x66, 0xce, 0xdc, 0xc6, 0xd3,
	0xe4, 0x1c, 0x36, 0xa6, 0xbe, 0xbb, 0xe4, 0x49, 0x82, 0x73, 0x9c, 0xf2, 0x50, 0xcf, 0xa5, 0xcb,
	0x92, 0x2f, 0xb0, 0x16, 0x9f, 0x27, 0xa2, 0xcd, 0xe6, 0x99, 0x9a, 0x63, 0xa5, 0x9d, 0xe4, 0x1b,
	0x62, 0x16, 0xca, 0xc4, 0x84, 0xc2, 0xe4, 0x6c, 0x91, 0xfa, 0x02, 0xb4, 0x6b, 0x5e, 0xad, 0x5c,
	0xe9, 0xd9, 0xe5, 0xb0, 0x0a, 0xdb, 0x72, 0x08, 0x74, 0x39, 0xac, 0x56, 0x60, 0xb3, 0x69, 0x23,
	0x9b, 0x42, 0x32, 0x31, 0x48, 0xdf, 0x86, 0x55, 0xb1, 0x20, 0xec, 0xed, 0xbf, 0x7d, 0xda, 0xb1,
	0x58, 0xb7, 0xdf, 0xac, 0x99, 0xce, 0xb9, 0xe6, 0xf5, 0x5d, 0xa4, 0xee, 0xce, 0x0e, 0xd3, 0x3a,
	0x8e, 0xdb, 0x45, 0x6a, 0x52, 0xa3, 0xcd, 0x34, 0x1f, 0x50, 0x6b, 0x76, 0x3c, 0x2d, 0x04, 0xd5,
	0x42, 0x50, 0xed, 0xa2, 0xfe, 0x55, 0xf8, 0xef, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xe0,
	0x30, 0xf4, 0xa7, 0x0a, 0x00, 0x00,
}
