// Code generated by protoc-gen-gcraft. DO NOT EDIT.
// source: entity_types.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EntityId struct {
	High                 *uint64  `protobuf:"fixed64,1,req,name=high" json:"high,omitempty"`
	Low                  *uint64  `protobuf:"fixed64,2,req,name=low" json:"low,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityId) Reset()         { *m = EntityId{} }
func (m *EntityId) String() string { return proto.CompactTextString(m) }
func (*EntityId) ProtoMessage()    {}
func (*EntityId) Descriptor() ([]byte, []int) {
	return fileDescriptor_05e1524293cd6d66, []int{0}
}

func (m *EntityId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityId.Unmarshal(m, b)
}
func (m *EntityId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityId.Marshal(b, m, deterministic)
}
func (m *EntityId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityId.Merge(m, src)
}
func (m *EntityId) XXX_Size() int {
	return xxx_messageInfo_EntityId.Size(m)
}
func (m *EntityId) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityId.DiscardUnknown(m)
}

var xxx_messageInfo_EntityId proto.InternalMessageInfo

func (m *EntityId) GetHigh() uint64 {
	if m != nil && m.High != nil {
		return *m.High
	}
	return 0
}

func (m *EntityId) GetLow() uint64 {
	if m != nil && m.Low != nil {
		return *m.Low
	}
	return 0
}

type Identity struct {
	AccountId            *EntityId `protobuf:"bytes,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	GameAccountId        *EntityId `protobuf:"bytes,2,opt,name=game_account_id,json=gameAccountId" json:"game_account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_05e1524293cd6d66, []int{1}
}

func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (m *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(m, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetAccountId() *EntityId {
	if m != nil {
		return m.AccountId
	}
	return nil
}

func (m *Identity) GetGameAccountId() *EntityId {
	if m != nil {
		return m.GameAccountId
	}
	return nil
}

func init() {
	proto.RegisterType((*EntityId)(nil), "bgs.protocol.EntityId")
	proto.RegisterType((*Identity)(nil), "bgs.protocol.Identity")
}

func init() { proto.RegisterFile("entity_types.proto", fileDescriptor_05e1524293cd6d66) }

var fileDescriptor_05e1524293cd6d66 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8e, 0x31, 0x6b, 0xeb, 0x30,
	0x14, 0x85, 0xb1, 0xdf, 0xa3, 0xa4, 0x4a, 0x43, 0x8b, 0x86, 0x62, 0x32, 0x85, 0x40, 0x69, 0x26,
	0xcb, 0x04, 0xba, 0x16, 0x1a, 0xe8, 0xe0, 0x2d, 0x64, 0xec, 0x62, 0x6c, 0xeb, 0x46, 0x16, 0xc8,
	0xba, 0xc2, 0xba, 0xa6, 0xcd, 0xd8, 0x7f, 0x5e, 0x64, 0xc7, 0x25, 0xa5, 0xd0, 0xed, 0x5c, 0xf1,
	0x7d, 0x47, 0x87, 0x71, 0xb0, 0xa4, 0xe9, 0x54, 0xd0, 0xc9, 0x81, 0x4f, 0x5d, 0x87, 0x84, 0xfc,
	0xa6, 0x52, 0xe7, 0x58, 0xa3, 0x59, 0x3e, 0x28, 0x83, 0x55, 0x69, 0x0a, 0xf8, 0x20, 0xb0, 0x5e,
	0xa3, 0xf5, 0xe2, 0xa8, 0xc1, 0xc8, 0x02, 0x1d, 0x85, 0x6b, 0x24, 0x97, 0x8f, 0xbf, 0xb1, 0x16,
	0xbc, 0x2f, 0x15, 0xfc, 0x04, 0xd7, 0x19, 0x9b, 0xbd, 0x0e, 0x7f, 0xe6, 0x92, 0x73, 0xf6, 0xbf,
	0xd1, 0xaa, 0x49, 0xa2, 0x55, 0xbc, 0xb9, 0x3a, 0x0c, 0x99, 0xdf, 0xb1, 0x7f, 0x06, 0xdf, 0x93,
	0x78, 0x78, 0x0a, 0x71, 0xfd, 0x19, 0xb1, 0x59, 0x2e, 0xc7, 0xa1, 0xfc, 0x89, 0xb1, 0xb2, 0xae,
	0xb1, 0xb7, 0x54, 0x68, 0x99, 0x44, 0xab, 0x68, 0x33, 0xdf, 0xde, 0xa7, 0x97, 0x8b, 0xd3, 0xa9,
	0xfe, 0x70, 0x7d, 0x26, 0x73, 0xc9, 0x9f, 0xd9, 0xad, 0x2a, 0x5b, 0x28, 0x2e, 0xdc, 0xf8, 0x4f,
	0x77, 0x11, 0xf0, 0x97, 0xc9, 0xdf, 0xed, 0xd9, 0xa2, 0xb2, 0x40, 0xdf, 0xe0, 0x6e, 0x3e, 0x92,
	0xfb, 0x70, 0xbf, 0x6d, 0x95, 0xa6, 0xa6, 0xaf, 0xd2, 0x1a, 0x5b, 0xe1, 0x7b, 0x07, 0x9d, 0xcb,
	0x32, 0x12, 0x0a, 0x5d, 0x03, 0x5d, 0xdd, 0x95, 0x47, 0x12, 0x41, 0x16, 0x95, 0xf2, 0x62, 0x2a,
	0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x43, 0x3c, 0x34, 0x96, 0x7a, 0x01, 0x00, 0x00,
}
