// Code generated by protoc-gen-gcraft. DO NOT EDIT.
// source: voice_types.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VoiceJoinType int32

const (
	VoiceJoinType_VOICE_JOIN_NORMAL VoiceJoinType = 0
	VoiceJoinType_VOICE_JOIN_MUTED  VoiceJoinType = 1
)

var VoiceJoinType_name = map[int32]string{
	0: "VOICE_JOIN_NORMAL",
	1: "VOICE_JOIN_MUTED",
}

var VoiceJoinType_value = map[string]int32{
	"VOICE_JOIN_NORMAL": 0,
	"VOICE_JOIN_MUTED":  1,
}

func (x VoiceJoinType) Enum() *VoiceJoinType {
	p := new(VoiceJoinType)
	*p = x
	return p
}

func (x VoiceJoinType) String() string {
	return proto.EnumName(VoiceJoinType_name, int32(x))
}

func (x *VoiceJoinType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(VoiceJoinType_value, data, "VoiceJoinType")
	if err != nil {
		return err
	}
	*x = VoiceJoinType(value)
	return nil
}

func (VoiceJoinType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a68d47a8c9ebf707, []int{0}
}

type VoiceMuteReason int32

const (
	VoiceMuteReason_VOICE_MUTE_REASON_NONE                         VoiceMuteReason = 0
	VoiceMuteReason_VOICE_MUTE_REASON_PARENTAL_CONTROL_LISTEN_ONLY VoiceMuteReason = 1
	VoiceMuteReason_VOICE_MUTE_REASON_REQUESTED                    VoiceMuteReason = 2
	VoiceMuteReason_VOICE_MUTE_REASON_SQUELCHED                    VoiceMuteReason = 3
)

var VoiceMuteReason_name = map[int32]string{
	0: "VOICE_MUTE_REASON_NONE",
	1: "VOICE_MUTE_REASON_PARENTAL_CONTROL_LISTEN_ONLY",
	2: "VOICE_MUTE_REASON_REQUESTED",
	3: "VOICE_MUTE_REASON_SQUELCHED",
}

var VoiceMuteReason_value = map[string]int32{
	"VOICE_MUTE_REASON_NONE":                         0,
	"VOICE_MUTE_REASON_PARENTAL_CONTROL_LISTEN_ONLY": 1,
	"VOICE_MUTE_REASON_REQUESTED":                    2,
	"VOICE_MUTE_REASON_SQUELCHED":                    3,
}

func (x VoiceMuteReason) Enum() *VoiceMuteReason {
	p := new(VoiceMuteReason)
	*p = x
	return p
}

func (x VoiceMuteReason) String() string {
	return proto.EnumName(VoiceMuteReason_name, int32(x))
}

func (x *VoiceMuteReason) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(VoiceMuteReason_value, data, "VoiceMuteReason")
	if err != nil {
		return err
	}
	*x = VoiceMuteReason(value)
	return nil
}

func (VoiceMuteReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a68d47a8c9ebf707, []int{1}
}

type VoiceProviderVersion int32

const (
	VoiceProviderVersion_VOICE_PROVIDER_V4 VoiceProviderVersion = 0
	VoiceProviderVersion_VOICE_PROVIDER_V5 VoiceProviderVersion = 1
)

var VoiceProviderVersion_name = map[int32]string{
	0: "VOICE_PROVIDER_V4",
	1: "VOICE_PROVIDER_V5",
}

var VoiceProviderVersion_value = map[string]int32{
	"VOICE_PROVIDER_V4": 0,
	"VOICE_PROVIDER_V5": 1,
}

func (x VoiceProviderVersion) Enum() *VoiceProviderVersion {
	p := new(VoiceProviderVersion)
	*p = x
	return p
}

func (x VoiceProviderVersion) String() string {
	return proto.EnumName(VoiceProviderVersion_name, int32(x))
}

func (x *VoiceProviderVersion) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(VoiceProviderVersion_value, data, "VoiceProviderVersion")
	if err != nil {
		return err
	}
	*x = VoiceProviderVersion(value)
	return nil
}

func (VoiceProviderVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a68d47a8c9ebf707, []int{2}
}

type VoiceCredentials struct {
	VoiceId              *string          `protobuf:"bytes,1,opt,name=voice_id,json=voiceId" json:"voice_id,omitempty"`
	Token                *string          `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Url                  *string          `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	JoinType             *VoiceJoinType   `protobuf:"varint,4,opt,name=join_type,json=joinType,enum=bgs.protocol.VoiceJoinType" json:"join_type,omitempty"`
	MuteReason           *VoiceMuteReason `protobuf:"varint,5,opt,name=mute_reason,json=muteReason,enum=bgs.protocol.VoiceMuteReason" json:"mute_reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *VoiceCredentials) Reset()         { *m = VoiceCredentials{} }
func (m *VoiceCredentials) String() string { return proto.CompactTextString(m) }
func (*VoiceCredentials) ProtoMessage()    {}
func (*VoiceCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_a68d47a8c9ebf707, []int{0}
}

func (m *VoiceCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoiceCredentials.Unmarshal(m, b)
}
func (m *VoiceCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoiceCredentials.Marshal(b, m, deterministic)
}
func (m *VoiceCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoiceCredentials.Merge(m, src)
}
func (m *VoiceCredentials) XXX_Size() int {
	return xxx_messageInfo_VoiceCredentials.Size(m)
}
func (m *VoiceCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_VoiceCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_VoiceCredentials proto.InternalMessageInfo

func (m *VoiceCredentials) GetVoiceId() string {
	if m != nil && m.VoiceId != nil {
		return *m.VoiceId
	}
	return ""
}

func (m *VoiceCredentials) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *VoiceCredentials) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *VoiceCredentials) GetJoinType() VoiceJoinType {
	if m != nil && m.JoinType != nil {
		return *m.JoinType
	}
	return VoiceJoinType_VOICE_JOIN_NORMAL
}

func (m *VoiceCredentials) GetMuteReason() VoiceMuteReason {
	if m != nil && m.MuteReason != nil {
		return *m.MuteReason
	}
	return VoiceMuteReason_VOICE_MUTE_REASON_NONE
}

func init() {
	proto.RegisterEnum("bgs.protocol.VoiceJoinType", VoiceJoinType_name, VoiceJoinType_value)
	proto.RegisterEnum("bgs.protocol.VoiceMuteReason", VoiceMuteReason_name, VoiceMuteReason_value)
	proto.RegisterEnum("bgs.protocol.VoiceProviderVersion", VoiceProviderVersion_name, VoiceProviderVersion_value)
	proto.RegisterType((*VoiceCredentials)(nil), "bgs.protocol.VoiceCredentials")
}

func init() { proto.RegisterFile("voice_types.proto", fileDescriptor_a68d47a8c9ebf707) }

var fileDescriptor_a68d47a8c9ebf707 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xae, 0x57, 0x26, 0xb6, 0xc3, 0x9f, 0x67, 0x15, 0x14, 0x98, 0x10, 0x13, 0x57, 0x53, 0x2f,
	0x92, 0xa9, 0x1a, 0x12, 0x17, 0x08, 0xa9, 0xb4, 0x96, 0xc8, 0x94, 0xc6, 0x9d, 0x9b, 0x46, 0x82,
	0x1b, 0xab, 0x4d, 0x4c, 0xe6, 0xd1, 0xc6, 0x91, 0xe3, 0x4c, 0xda, 0xf3, 0xf0, 0x40, 0xbc, 0x12,
	0x8a, 0x3b, 0x60, 0xd0, 0xde, 0x7d, 0xe7, 0xf3, 0xf7, 0x73, 0x7c, 0xe0, 0xe8, 0x46, 0xab, 0x4c,
	0x0a, 0x7b, 0x5b, 0xc9, 0xda, 0xaf, 0x8c, 0xb6, 0x9a, 0x3c, 0x5e, 0x16, 0x77, 0x30, 0xd3, 0xab,
	0xb7, 0x3f, 0x11, 0xe0, 0xb4, 0xd5, 0x8c, 0x8c, 0xcc, 0x65, 0x69, 0xd5, 0x62, 0x55, 0x93, 0x97,
	0x70, 0xb0, 0xf1, 0xa9, 0xdc, 0x43, 0x27, 0xe8, 0xf4, 0x90, 0x3f, 0x74, 0x73, 0x98, 0x93, 0x1e,
	0xec, 0x5b, 0xfd, 0x5d, 0x96, 0xde, 0x9e, 0xe3, 0x37, 0x03, 0xc1, 0xd0, 0x6d, 0xcc, 0xca, 0xeb,
	0x3a, 0xae, 0x85, 0xe4, 0x3d, 0x1c, 0x5e, 0x6b, 0x55, 0xba, 0x66, 0xef, 0xc1, 0x09, 0x3a, 0x7d,
	0x3a, 0x38, 0xf6, 0xef, 0x37, 0xfb, 0xae, 0xf5, 0x42, 0xab, 0x32, 0xb9, 0xad, 0x24, 0x3f, 0xb8,
	0xbe, 0x43, 0xe4, 0x23, 0x3c, 0x5a, 0x37, 0x56, 0x0a, 0x23, 0x17, 0xb5, 0x2e, 0xbd, 0x7d, 0xe7,
	0x7d, 0xbd, 0xc3, 0x3b, 0x69, 0xac, 0xe4, 0x4e, 0xc4, 0x61, 0xfd, 0x07, 0xf7, 0x3f, 0xc0, 0x93,
	0x7f, 0xa2, 0xc9, 0x73, 0x38, 0x4a, 0x59, 0x38, 0xa2, 0xe2, 0x82, 0x85, 0xb1, 0x88, 0x19, 0x9f,
	0x0c, 0x23, 0xdc, 0x21, 0x3d, 0xc0, 0xf7, 0xe8, 0xc9, 0x3c, 0xa1, 0x63, 0x8c, 0xfa, 0x3f, 0x10,
	0x3c, 0xfb, 0x2f, 0x9d, 0xbc, 0x82, 0x17, 0x1b, 0x65, 0x2b, 0x12, 0x9c, 0x0e, 0x67, 0xac, 0xcd,
	0x89, 0x29, 0xee, 0x90, 0x01, 0xf8, 0xdb, 0x6f, 0xd3, 0x21, 0xa7, 0x71, 0x32, 0x8c, 0xc4, 0x88,
	0xc5, 0x09, 0x67, 0x91, 0x88, 0xc2, 0x59, 0x42, 0x63, 0xc1, 0xe2, 0xe8, 0x0b, 0x46, 0xe4, 0x0d,
	0x1c, 0x6f, 0x7b, 0x38, 0xbd, 0x9c, 0xd3, 0x59, 0xbb, 0xc4, 0xde, 0x6e, 0xc1, 0xec, 0x72, 0x4e,
	0xa3, 0xd1, 0x67, 0x3a, 0xc6, 0xdd, 0xfe, 0x18, 0x7a, 0x6e, 0xc9, 0xa9, 0xd1, 0x37, 0x2a, 0x97,
	0x26, 0x95, 0xa6, 0x56, 0xba, 0xfc, 0xfb, 0xd5, 0x29, 0x67, 0x69, 0x38, 0xa6, 0x5c, 0xa4, 0xe7,
	0xb8, 0xb3, 0x8b, 0x7e, 0x87, 0xd1, 0xa7, 0xf3, 0xaf, 0x83, 0x42, 0xd9, 0xab, 0x66, 0xe9, 0x67,
	0x7a, 0x1d, 0xd4, 0x4d, 0x25, 0x4d, 0x75, 0x76, 0x66, 0x83, 0x42, 0x57, 0x57, 0xd2, 0x64, 0x66,
	0xf1, 0xcd, 0x06, 0xcb, 0x52, 0xda, 0x60, 0x59, 0xd4, 0xc1, 0xef, 0xdb, 0xff, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0x33, 0x2d, 0x6d, 0x95, 0x53, 0x02, 0x00, 0x00,
}
